src/components/inputs/InputTemperature.vue, src/components/widgets/ExtruderMovesWidget.vue
On the dashboard, clicking input puts the cursor in the box. On tablet/mobile, this causes you to have to click - then double click to highlight or click and delete to change input values.
This change automatically selects the value of the input box so you can just type a number and hit enter.
=> auto select text on click on dashboard

src/components/widgets/history/ReprintMenu.vue
=> Fixed a small glitch in the reprint menu

src/components/widgets/console/ConsoleCard.vue, src/components/widgets/console/ConsoleCommand.vue
The help message was truncated and can be even longer with languages other than English.
Before:
After:
=> feat(console-help): Moved console help to a tooltip

src/mixins/files.ts
When we download a file, we create a temporary link with a
download attribute. We then programatically click on it,
on Firefox this closes any ongoing WebSocket connection which
causes the application to go in a "disconnected" state.
See here for additional informations:
https://bugzilla.mozilla.org/show_bug.cgi?id=858538
https://bugzilla.mozilla.org/show_bug.cgi?id=896666
Until this is fixed, we added a `target="_blank"` attribute
as a workaround.
=> fix(firefox-download): Fix ws disconnecting when downloading

.github/workflows/multiarch_dockerhub.yml
I got Klipper and Mainsail running on a Raspberry Pi Zero (see https://github.com/dimalo/klipper-web-control-docker/issues/7, needed ARM32v6 images built and Docker 20), but Fluidd is also lacking ARM32v6 images
=> Build ARMv6 Docker images for Raspberry Pi Zero

src/mixins/files.ts
With `privacy.resistFingerprinting` enabled in Firefox-based browsers the precision of `performance.now()` is reduced to 100 ms. On most machines I've tested this leads to a division by zero in the transfer progress speed calculation when the a file upload/download starts (in less than 100 ms), subsequently the script enters an infinite loop (as speed is assigned `Infinity`) and the tab freezes. Fix this by explicitly requiring a positive delta before starting to calculate transfer speed, I can confirm that editing and saving files through Fluidd now works on all affected machines on my end.
Signed-off-by: Dennis Marttinen <twelho@welho.tech>
=> fix: division by zero and infinite loop in file upload/download dialogs

src/components/widgets/status/PrintStatus.vue, src/plugins/filters.ts, src/store/printer/getters.ts, src/store/printer/types.ts, tests/unit/filters.spec.ts
Addresses #295.
Adds an estimate of the real-world print completion estimation to the print status card.  Has three main states:
- Hidden when not printing
- When the estimate is in the same day a straight hours/minutes end estimate is given
- When the estimate is further in the future the estimated end date is also included
=> Add absolute end time estimate

src/components/widgets/gcode-preview/GcodePreviewCard.vue
Under certain (currently unknown) conditions, `fileMovePosition` can get out of sync with `moveProgress` on some layer changes, disabling the follow progress feature.
This is a naive attempt at addressing this based on some existing logic.
=> Bugfix: gcode viewer stops following progress between layers

Dockerfile
Changed image used for stage "unzip"; alpine is much smaller and does not need unzip installed.
Removed ARG declared but never referenced.
Removed RUN previously used to install unzip in debian container.
Removed stage name "image" declared but never referenced.
Removed commented lines.
=> Dockerfile Cleanup

src/store/helpers.ts
Requires https://github.com/fluidd-core/FluiddPI/pull/9 for NGINX IPv6 support
---
IPv6 support for encodeURI() is [broken](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI#encoding_for_ipv6).
Mozilla's fix for this is, however, dirty, and may break other URLs.
This PR replaces encodeURI() with an implementation using the URL API, fully supporting IPv6.
Assumes the document origin as a default location when no `apiUrl` is set, as an empty URL() constructor is forbidden. An `apiUrl` is (should?) always be set, however, because the thumbnails will only be retrieved after adding a backend.
---
Mainsail solves this by not encoding the URI at all, not sure if this is feasible here: https://github.com/meteyou/mainsail/blob/5dbffdb1675ccdfc84211ab53cd0519 …
=> fix: IPv6 support for thumbnails

src/components/widgets/filesystem/FileSystemBrowser.vue
Currently, when selecting `n-1` files of a file system browser with `n` files, all files are selected. This PR fixes the broken logic for determining if all files should be selected.
=> fix: file system browser selection

src/components/settings/cameras/CameraConfigDialog.vue, src/components/widgets/camera/CameraItem.vue, src/locales/en.yaml, src/store/cameras/index.ts, src/store/cameras/types.ts
Hi :)
I just started setting up my klipper setup with fluidd and found out that you can not setup camera as a simple iframe.
I am using https://github.com/dans98/pi-h264-to-browser with works much better then any mjpeg options.
Uses less bandwidth and runs with hw accel in your browser but needs to be setup as a simple web page.
So I add an iframe option named "HTTP Page".
I also add to it an height option, it is a not perfect workaround around the iframe not scaling automatic.
Another option to fix that would be onLoad on the iframe but that would work only if the webserwer and camera are on the same origin with isn't always the case.
My first time writing code for vue, so any suggestion are welcome if something isn't up to the standards. 
In general works really well:
=> Add camera iframe option with height option

src/components/common/SystemCommands.vue, src/components/settings/GeneralSettings.vue, src/locales/en.yaml, src/store/config/index.ts, src/store/config/types.ts
Implements #386, by adding a new setting that allow to indicate if a confirmation dialog should be shown when the user toggles a device power.
=> feat: adds optional confirmation for power device toggle

src/components/widgets/outputs/OutputFan.vue, src/locales/en.yaml
Changing the status of uncontrollable fan to On/Off instead of useless percentage.
In the same minding of this #391 .
Signed-off by Biorn : biorn@me.com
=> Feat: Non-controllable fan On/Off

src/components/widgets/camera/CameraMenu.vue
This leaves the camera select menu enabled even when klipper is disconnected.
For issue: https://github.com/fluidd-core/fluidd/issues/470
=> fix: keep camera select menu always enabled

src/components/common/AppWarnings.vue, src/store/printer/getters.ts, src/store/printer/index.ts
Here's an example for a deprecated configuration option.
I haven't added any link back to Klipper docs but want to put that into consideration before merging this PR!
=> feat: show klipper warnings

src/plugins/socketClient.ts
- DeepMerge was appending the array instead of merging.
Thanks @pedrolamas
Signed-of-by: Biorn <biorn@me.com>
=> fix: websocket cache issue (arrayMerge)

src/locales/de.yaml
Took some time today to go through all the German translations and fix a couple small linguistic errors and add the missing few translations.
I used BabelEdit for this (as recommended in [the docs](https://docs.fluidd.xyz/development/localization#how-to-contribute)), so it automatically applied its formatting. Not sure if this is a problem, if it is please let me know so I can manually re-format it.
Closes #321
=> i18n: improve and finish german translations

src/components/ui/AppChart.vue, src/components/widgets/bedmesh/BedMeshChart.vue, src/components/widgets/thermals/ThermalChart.vue
These were introduced as part of the work for Node 16 support, but we've now come to realize that not only are they not needed, but they are also creating a layout issue on the charts.
=> fix: revert ECharts changes previously introduced

src/components/widgets/console/Console.vue, src/components/widgets/console/ConsoleCard.vue, src/locales/en.yaml
When scrolled up, it will "pause" the auto scroll to bottom until you scroll down or click the button to scroll back to the bottom. The button will only be displayed when scrolling is "paused".
This is for https://github.com/fluidd-core/fluidd/issues/343
This was lightly tested with Firefox and Edge in Ubuntu.  Additional testing would be appreciated.
=> feat: pause autoscroll when back scrolling

src/components/ui/AppMacroBtn.vue
Improves the regular expression used to detect macro parameter defaults. This should be a bit more permissive with white-space and multiple params on the Jinja2 `default` function.
Tested with the following example:
```txt
[gcode_macro TEST]
gcode:
{% set A = params.A | default(0, true) | float %}
{% set B = params.B | int | default(0.005, true) | float %}
{% set C = params.C | default("PLA", true) %}
{% set D = params.D | default("PLA") %}
{% set E = params.E | int | default(0.2) %}
```
The above example macro will show like this:
Fixes #376 
=> fix: improves macro param default value handling

src/components/widgets/console/Console.vue, src/components/widgets/console/ConsoleCard.vue, src/locales/de.yaml, src/locales/en.yaml, src/store/config/index.ts, src/store/config/types.ts
Adds an option to move the console input field to the top of the console widget.
Not sure if the log direction should be flipped too (most recent at top), and if "Flip layout" is the right wording here.
Closes #511
=> feat: option to flip console direction

src/components/widgets/thermals/TemperatureCard.vue, src/locales/de.yaml, src/locales/en.yaml
As requested by NewCalJs in the Discord server.
Adds a confirmation modal to the `Heaters off` button under temperature presets when the printer is busy.
=> feat: TURN_OFF_HEATERS confirmation in temperature presets

src/components/widgets/toolhead/ToolheadMoves.vue
This partially reverts commit d9316467e172738a855e42d08fe2db2bbff1bb50
Fixes #528
=> fix: reverts homing override checks in ToolheadMoves.vue

src/components/settings/cameras/Cameras.vue, src/store/cameras/index.ts
Adds the missing type and default value for the "FPS Target when not in focus" input field in the "Add Camera" dialog
=> fix: add missing default for idle fps input

src/components/widgets/status/StatusLabel.vue, src/components/widgets/status/StatusTab.vue
This issue has bothered me for some time and I figured I would attempt to fix it. If this is not the "best" way to do this please let me know. Tested in several browsers and iOS 15.
**Before the changes:**
**After the changes:**
Signed-off-by: Phillip Hernandez samwiseg00@gmail.com
=> fix: filename wrap in status window

src/App.vue
Simply adds a 8px margin to the left and bottom of the emergency stop button, moving it back into the iPhone safe area
before:
after:
Closes #405
=> fix: emergency stop button outside iphone safe zone

src/components/widgets/thermals/ThermalChart.vue, src/store/charts/getters.ts, src/store/printer/actions.ts, src/store/server/index.ts, src/store/server/types.ts
We were lucky as @majcn found the problem was with the `temperature_store_size` (it can be in either `data_store` or `server`)
I've managed to confirm and reproduce the incorrect behavior, and this PR should fix the problem completely.
Special thanks also to @BeardedTinker and @Arksine for helping with this issue.
Fixes #453
=> fix: use correct temperature_store_size for temps

docs/configuration/moonraker.md, docs/configuration/moonraker_conf.md
Moonraker changed configuration structure some time ago. fluidd was only using `server` part which is now in `data_store` and `file_manager`,...
I removed code part of changing things which are solved https://github.com/fluidd-core/fluidd/pull/555 and only left docs part
=> docs: moonraker config refactor

package-lock.json, package.json
There is no reference to the [vuex-class](https://www.npmjs.com/package/vuex-class) package anywhere on the code (in fact, from what I can see on the package instructions, we have it incorrectly added as a dev dependency when it should be a regular one), so I'm removing it here.
=> chore: removes unused vuex-class dependency

package-lock.json, package.json, src/App.vue, src/main.ts, src/vue-headful.d.ts
[vue-headful](https://www.npmjs.com/package/vue-headful) has been marked as deprecated with a note to use [vue-meta](https://www.npmjs.com/package/vue-meta), which we already do anyway!
So I've completely removed the deprecated vue-headful dependency and ensured that we only use the correct vue-meta.
=> chore: removes deprecated vue-headful dependency

src/components/widgets/status/PrinterStatusCard.vue
=> feat(ui): display localized printer state in printer status card

src/components/ui/AppMacroBtn.vue
Fixes issue introduced with #524, were a macro parameter with no default value would not show up in the interface.
Tested with the following example:
```
[gcode_macro TEST]
gcode:
{% set A = params.A | default(0, true) | float %}
{% set B = params.B | int | default(0.005, true) | float %}
{% set C = params.C | default("PLA", true) %}
{% set D = params.D | default("PLA") %}
{% set E = params.E | int | default(0.2) %}
{% set F = params.F %}
```
Before (F missing):
After (F showing):
=> fix: shows missing macro parameters

src/components/ui/AppColorPicker.vue, src/components/widgets/outputs/OutputLed.vue
Adds a draggable title to the color picker card - now they can be moved anywhere you'd like ;)
Closes #332
=> feat(ui): make color picker movable

.github/workflows/build.yml, .github/workflows/release.yml
This will make installing the dependency packages faster and ensure reproducible builds by only installing locked versions.
=> chore: use locked dependency versions on server

src/components/widgets/filesystem/FileEditorDialog.vue
=> feat: unsaved editor close confirmations when unloading the page

.github/workflows/release.yml
GitHub release notes keep showing incorrect (old) data.
Seems the [changelog-reader-action](https://github.com/mindsers/changelog-reader-action) is the problem here, so I'm updating the workflow to specify the correct version to read, following their own example on how to do this.
=> chore: fix GitHub release description

src/components/widgets/toolhead/ExtruderMoves.vue, src/views/Dashboard.vue
Missing typing in Dashboard.vue, and a typo ("onExtract" instead of "onExtrude") on ExtruderMoves.vue
=> chore: more typescript typings

src/components/widgets/toolhead/PressureAdvanceAdjust.vue, src/components/widgets/toolhead/Toolhead.vue, src/globals.ts, src/locales/en.yaml, src/store/printer/getters.ts
Adds Pressure Advance and Smooth Time settings to the Tool panel.
I considered putting this on a new separate panel, but it made sense to be on the Tool as the Extruder selection is made here and in the end, these settings are in regards to the current active extruder!
I also took into consideration putting this under the Tune page, but this is one of those settings that does depend on the type of filament you are currently printing, so it is not as static as the bed mesh, for example.
=> feat: adds Pressure Advance support

.browserslistrc
By changing the browser support to only mainstream browsers (Chrome, Edge, Safari, Opera, Firefox) will increase build speed and reduce resources!
Browser coverage drops from 90% to 88%, but I don't think this is significant:
- [Current coverage](https://browserslist.dev/?q=PiAxJSxsYXN0IDIgdmVyc2lvbnMsbm90IGRlYWQ%3D)
- [Proposed coverage](https://browserslist.dev/?q=PiAxJSxub3QgZGVhZCxsYXN0IDIgY2hyb21lIG1ham9yIHZlcnNpb25zLGxhc3QgMiBmaXJlZm94IG1ham9yIHZlcnNpb25zLGxhc3QgMiBzYWZhcmkgbWFqb3IgdmVyc2lvbnMsbGFzdCAyIG9wZXJhIG1ham9yIHZlcnNpb25zLGxhc3QgMiBlZGdlIG1ham9yIHZlcnNpb25z)
=> chore: drop support for unused browsers

src/components/ui/AppSlider.vue, src/components/widgets/toolhead/PressureAdvanceAdjust.vue, src/locales/en.yaml, src/types/vuetify.ts
This should hopefully allow to enter "0.02" on text field and still work correctly!
Tested under Edge and Firefox.
Fixes #603 
=> fix: allow decimals in slider bound text controls

src/components/widgets/filesystem/FileEditor.vue, src/components/widgets/filesystem/setupMonaco.ts, src/main.ts
This allows the Monaco editor component to be asynchronously loaded when needed.
The vendor chunk is reduced from 5642.22 KiB  to 2953.59 KiB.
The new chunk weights 2716.54 KiB.
The size could be reduced by shaving off editor features.
Available features are `'accessibilityHelp' | 'anchorSelect' | 'bracketMatching' | 'caretOperations' | 'clipboard' | 'codeAction' | 'codelens' | 'colorPicker' | 'comment' | 'contextmenu' | 'coreCommands' | 'cursorUndo' | 'dnd' | 'documentSymbols' | 'find' | 'folding' | 'fontZoom' | 'format' | 'gotoError' | 'gotoLine' | 'gotoSymbol' | 'hover' | 'iPadShowKeyboard' | 'inPlaceReplace' | 'indentation' | 'inlayHints' | 'inlineCompletions' | 'inspectTokens' | 'lineSelection' | 'linesOperations' | 'linkedEditing' | 'links' | 'multicursor' | 'parameterHints' | …
=> chore: split FileEditor into a separate chunk

src/components/ui/AppColorPicker.vue
On Firefox desktop, we get undefined references errors to `window.TouchEvent` in the console when the color picker is loaded.
=> fix: TouchEvent is not defined on Firefox desktop

src/components/widgets/toolhead/Toolhead.vue, src/components/widgets/toolhead/ZHeightAdjust.vue
Fixes incorrect wrapping of Z-offset controls
Before:
After:
=> fix: Toolhead and ZHeightAdjust layout

src/store/helpers.ts
Noticed that a thumbnail was not displaying when i uploaded a gcode file with "infill 10%" in its name. Turned out the thumbnail name is basically the gcode name and also contained the % character which was not url encoded. Fixed that and also for the path, as the same problem may happen there.
The gcode name was auto-generated by the cura "Gcode Filename Format Plus" plugin.
=> Added thumbnail URI encoding

src/store/helpers.ts
This was incorrectly added to master branch when it should have got to develop, so reverting master changes now
This reverts commit 30efd5ff12848c1c7e7dda654c7cee4a7feb0f65.
=> Revert "fix: thumbnail URI encoding (#618)"

src/components/common/SystemPrinters.vue, src/components/layout/AppBar.vue, src/components/settings/VersionSettings.vue, src/components/widgets/filesystem/FileNameDialog.vue, src/components/widgets/filesystem/FileSystem.vue, src/components/widgets/gcode-preview/GcodePreviewCard.vue
As it currently stands, most dialogs are loaded on the Vue object tree but kept hidden until needed, something I believe we actually do not need, so this PR changes that!
Before:
After:
The `UpdatingDialog` works a bit differently, so that one I kept as is.
I've also fixed a bug on the `FileNameDialog`, where clicking outside the dialog would close it but we wouldn't be able to open it again!
=> fix: fully unload dialogs when not in use

src/components/widgets/filesystem/FileSystemBrowser.vue, src/plugins/filters.ts
=> feat: formats weight as human readable

src/store/layout/mutations.ts
Fixes an issue where the moonraker db entry for the layout would be missing a whole side (container) of the dashboard, making other components fail to load:
```
mutations.ts:46 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'push')
at mutations.ts:46:50
at Array.forEach (<anonymous>)
at mutations.ts:44:27
at v.setInitLayout (mutations.ts:22:53)
```
=> fix: layout database data handling

src/store/printer/getters.ts
Klipper calculates progress by calculating `current_file_position / file_length`, but that can lead to progress starting on a non 0% value and the print complete before it reaches 100% (in my tests, I've seen it start at 46% and end at 97%)
The reason for this is that G-code files can have a lot of metadata on the start (thumbnails for example) and end of the file, thus causing the above problem.
As Moonraker reports the start byte and end byte of the G-code, we can use that together with the current file position and calculate a more correct progress value!
Having a "better" progress value will also lead to more accurate timing reports!
Before:
After:
=> feat: calculate linear progress

src/components/widgets/filesystem/FileEditor.vue, src/components/widgets/filesystem/FileEditorDialog.vue, src/components/widgets/filesystem/FileEditorTextOnly.vue, src/util/is-mobile.ts
Monaco Editor is not supported on mobile devices (it says so on [their page](https://microsoft.github.io/monaco-editor/)), so instead of having a broken editing experience in mobile devices, better to just use a simple text area!
This change can be easily tested by changing the browser User Agent to a mobile one.
Screenshot from my own OnePlus Android phone:
Fixes #380
=> fix: show simple editor on mobile

src/components/ui/AppMacroBtn.vue, src/util/__tests__/gcode-macro-params.spec.ts, src/util/gcode-macro-params.ts
Tested with the following example:
```
[gcode_macro TEST]
gcode:
{% set A = params.A | default(0, true) | float %}
{% set B = params.B | int | default(0.005, true) | float %}
{% set C = params.C | default("PLA", true) %}
{% set D = params.D | default("PLA") %}
{% set E = params.E | int | default(0.2) %}
{% set F = params.F|default(printer.configfile.settings.printer.max_velocity)|int %}
{% set G = params.G|default("this \"works\"")|int %}
```
Before (F has default value when should not):
After (no default value on F):
Refactored the gcode macro params default values parsing so we can easily run a suite of tests on it.
Fixes #650
=> fix: improves macro params default values parsing

src/components/widgets/toolhead/PressureAdvanceAdjust.vue
Run `SET_PRESSURE_ADVANCE ADVANCE=0.096 SMOOTH_TIME=0.025`
Before:
After:
Scrolling does perform quite slower like this, but should still work fine!
=> fix: increase PA precision to 0.001

src/components/ui/AppSlider.vue, src/components/widgets/outputs/OutputFan.vue
Issue caused by AppSlider.vue changes in 863c0b289b3de522dbef64767b881960654acd16
This reverts most of those changes as I came to realize that one can use `v-model.number` to force a bind as number...
Though AppSlider value is `number`, the rules will also be used for a non-valid number, so I added a `+` safeguard on OutputFan to ensure a number/NaN is in use.
Fixes #653
=> fix: AppSlider incorrect state

src/components/widgets/thermals/TemperatureTargets.vue
Minor UI issue, caused by the fact `selectedLegends = {}` is the default state when we start a new install, and that incorrectly shows the items as disabled.
Before:
After:
The default is all temp items selected, so let's show that accordingly!
=> fix: show temp item as selected by default

src/components/widgets/thermals/TemperatureTargets.vue
Continuation of #655, the same fix needs to be applied to `fans` and `sensors` elements
=> fix: show temp item as selected by default (cont.)

src/workers/parseGcode.ts
Ensures that the gcode parser can accept ".2" as a valid number (with omited "0" on unit)
This could be easily fixed just by this change:
```diff
- /([a-z])[ \t]*(-?\d+(?:\.\d+)?)/
+ /([a-z])[ \t]*(-?\d*(?:\.\d+)?)/
```
However, the above would allow for empty values (no number), so I opted for allowing the current or ".nnn".
Fixes #674
=> fix: allow omit 0 units in gcode number parsing

src/locales/fr.yaml
fix: Fix a typo in French translations: 
`app.version.label.updates_available`: `disponnibles` -> `disponibles`
Signed-off-by: Samori Gorse <samori@codeinstyle.io>
=> fix(i18n-FR): fix typo in French translation

.github/workflows/release.yml
At the moment the changelog-reader-action is unable to correctly find patch versions on the CHANGELOG, so our release pipeline is failing.
The issue was fixed here: https://github.com/mindsers/changelog-reader-action/commit/baf2b5f006e435331aa4ea25d1fcdee6c7a7a37d
Once a new upstream version of this action is release, we can revert this change (and update the action version), but for now we are using a personal fork of the action.
=> chore: temporary fix for release pipeline

src/components/widgets/toolhead/Toolhead.vue
Klipper doesn't seem to provide what `extruder_stepper` is currently active so Moonraker can't make it available to the API consumers.
The only way forward in this for now is to just "hide" the full Pressure Advance controls if no `pressure_advance` values are provided in the active extruder (meaning no stepper is set)
Fixes #681
=> fix: hide Pressure Advance if no default extruder stepper set

src/components/ui/AppSlider.vue
Noticed the mobile lock controls aren't actually disabled when the input is, causing some weird behavior
=> fix: AppSlider mobile lock disabling

src/components/widgets/gcode-preview/GcodePreview.vue, src/components/widgets/gcode-preview/GcodePreviewCard.vue, src/components/widgets/gcode-preview/GcodePreviewControls.vue
Moves the gcode preview related settings to a dropdown and fixes the layout to be compatible with vertical monitors
Not sure if the "Load current file" and "Clear file" buttons should also go there, LMK what you think..
Closes #690
=> fix(layout): move gcode controls to dropdown; fix vertical layout

docs/features/cameras.md
Removes the mention of old FluiddPi versions from the docs as it's causing confusion; refactors the instructions
Closes #403
=> docs(cameras): refactor configuration instructions

src/components/widgets/system/McuCard.vue, src/components/widgets/system/McuConstantsDialog.vue, src/components/widgets/system/SystemOverviewCard.vue, src/globals.ts, src/locales/de.yaml, src/locales/en.yaml, src/plugins/filters.ts, src/store/printer/types.ts, src/views/System.vue
Moves MCU information from System panel to separate panels (one for each MCU) and shows more information on dialog.
=> feat: moves MCU info to separate panel

src/components/ui/AppBtnCollapseGroup.vue, src/components/widgets/gcode-preview/GcodePreviewCard.vue, src/components/widgets/thermals/TemperatureCard.vue
Keep the mini buttons on the cards visible on mobile view (affects the Gcode Preview and Temperature cards only)
| before | after |
|--|--|
| ![image](https://user-images.githubusercontent.com/85504/173026763-ba5547f4-9087-406a-98cd-cba8e7ffa03e.png) | ![image](https://user-images.githubusercontent.com/85504/173026646-93c1086b-d7c8-4072-a6e3-eacd92ca3b02.png) |
=> feat: keep icon buttons visible on mobile view

src/api/httpClient.ts
Restarting Moonraker (via Fluidd option or when saving changes to "moonraker.conf") will show the below image, which is an expected error (connection close leads to network error)
This adds a further check for network error issues to the existing code.
=> fix: mitigates network error with latest Axios

src/components/settings/FileEditorSettings.vue, src/components/widgets/filesystem/FileEditor.vue, src/components/widgets/filesystem/FileEditorDialog.vue, src/locales/en.yaml, src/store/config/index.ts, src/store/config/types.ts
Adds new setting to control CodeLens visibility (defaults to true)
Fixes #711 
Fixes #713 
=> feat: adds setting to toggle Codelens visibility

docs/installation/fluiddpi.md
Signed-off-by: Abílio Costa <amfcalt@gmail.com>
=> docs: remove wrong http:// protocol from ssh instructions

src/components/widgets/toolhead/ToolheadPosition.vue, src/globals.ts, src/locales/en.yaml
Adds controls to change between relative/absolute positioning mode.
Related to #395
=> fix: show absolute/relative positioning controls

src/components/widgets/toolhead/ToolheadPosition.vue
=> fix: disable absolute/relative positioning controls while printing

src/components/widgets/toolhead/ToolheadPosition.vue
Signed-off-by: Mathis Mensing <matmen@dreadful.tech>
=> fix: disable positioning mode buttons when klippy is not ready

src/api/auth.api.ts, src/components/layout/AppUserMenu.vue, src/components/settings/auth/AuthSettings.vue, src/locales/en.yaml, src/store/auth/actions.ts, src/store/auth/types.ts, src/views/Login.vue
Adds a authentication source dropdown to the login page (only if LDAP authentication is configured) with the corresponding default:
Disables the corresponding user controls when a user is LDAP sourced:
=> feat: ldap authentication support

docs/authorization/index.md
add LDAP instructions to fluidd documentation
Signed-off-by: Luca Schöneberg [luca-schoeneberg@outlook.com](mailto:luca-schoeneberg@outlook.com)
=> docs: add LDAP instructions

src/components/ui/AppColorPicker.vue, src/components/widgets/outputs/OutputItem.vue, src/components/widgets/outputs/OutputLed.vue, src/components/widgets/outputs/Outputs.vue, src/store/printer/getters.ts, src/store/printer/types.ts
=> fix: LED controls behavior

src/components/layout/AppUserMenu.vue
This issue was introduced with the changes from #721, where we are now accessing `this.user` without performing a null check first!
=> fix: console error from LDAP auth changes

src/store/wait/mutations.ts
Currently, a call to `setRemoveWait` method with an item that is not part of the `state.waits` will still splice it, incorrectly removing the last item (basically, it will run `state.waits.splice(-1, 1)`)
This fix ensures that we do not splice if the item is not part of the `state.waits`.
=> fix: only splice waits if contains item

src/store/history/actions.ts
Check that `gcodes` root exists before attempting to list the files from it.
Fixes #727 
=> fix: check for root available before listing files

src/components/widgets/gcode-preview/GcodePreviewCard.vue
Minor fix/improvement for the layout of the gcode previewer.
=> fix: gcode preview initial layout

src/api/httpClient.ts
Quite a few times we've seen users reporting a 502 error, most of the times mentioning nginx, and I've finally managed to reproduce and fix it!
Nginx (and possibly other reverse proxies) will return 502 if they can't reach the server (moonraker), which is expected if we have just restarted the service from Fluidd (and thus a "/access/oneshot_token" call can happen)
=> fix: nginx 502 error when restarting moonraker

src/components/common/CollapsableCard.vue
Hi,
I am sure that this is a bug. For this reason I have added a small fix that checks whether the component is collapsable or not. If it is not collapsable, it must be in fullscreen mode and returns false (isCollapsed --> false). 
Here is a video to demonstrate it:
https://user-images.githubusercontent.com/44060099/177038733-a3963482-23e9-479d-8d9b-91db2b927d14.mov
And also for the fix:
https://user-images.githubusercontent.com/44060099/177038853-52b6a480-34d3-4bc4-b629-acdc9405d746.mov
=> fix: no collapsed console in fullscreen mode

src/components/layout/AppBar.vue, src/components/settings/GeneralSettings.vue, src/locales/de.yaml, src/locales/en.yaml, src/store/config/index.ts, src/store/config/types.ts
Closes: #729 
- Shutdown icon on AppBar/TopBar
- Entry in the settings to (de)activate
Here you can see it in action:
https://user-images.githubusercontent.com/44060099/177038146-131b4d90-e044-4868-8f4e-533ad995fa6f.mov
=> feat: add icon to shutdown on AppBar

src/components/settings/GcodePreviewSettings.vue, src/components/widgets/gcode-preview/GcodePreviewCard.vue, src/locales/de.yaml, src/locales/en.yaml, src/store/config/index.ts, src/store/config/types.ts, src/store/gcodePreview/actions.ts
Provides the following two new features:
* An option to automatically load the print file on print start
* An option to automatically follow progress on file load
I'm not 100% sure about the UX when auto-loading a file (the two popups seem annoying); maybe that can be moved to the background?
Closes #730
=> feat: Extended G-Code viewer auto-actions

src/components/widgets/filesystem/setupMonaco.ts, src/locales/en.yaml
Refactors Monaco setup to use existing configuration map and to expose Codelens support for moonraker-telegram-bot.
Fixes #741 
=> fix: codelens links for moonraker-telegram-bot

src/store/auth/mutations.ts
Adds a fallback `source` attribute to newly created users, making them always match their typedef.
Fixes the following bug:
=> fix: add default authentication source to new users

src/components/ui/AppSwitch.vue
=> fix(style): light theme AppSwitch

src/components/widgets/gcode-preview/GcodePreviewCard.vue, src/components/widgets/toolhead/ToolheadMoves.vue, src/components/widgets/toolhead/ToolheadPosition.vue, src/components/widgets/toolhead/ZHeightAdjust.vue
Some "shadows" were missing in toggle buttons, wrong colors used for gcode preview controls.
=> fix(style): light theme and consistency changes

src/components/widgets/outputs/OutputLed.vue
A couple of issues with this one, but I've now tested in Simulavr with `[led]`, `[neopixel]` and `[dotstar]` (containing 1 or more channels, with and without White channel), and I believe it will work for these and the other types of LEDs too!
> **Dev note:** though on some of these LED types we can specify a `color_order`, that does NOT change the output order of `color_data` - it is ALWAYS `[R, G, B, W]`)
> 
> ![image](https://user-images.githubusercontent.com/85504/178964798-56a0d0df-8475-4c2d-95fa-321984a39332.png)
> 
> Klipper also does not complain if we call `SET_LED` with all params, so I've decided to keep that in for now
Fixes #765
=> fix: OutputLed working with all types of LEDs

src/components/widgets/toolhead/ToolheadCard.vue
Adds the same conditional disabling to the FORCE_MOVE toggle that the other toolhead card header buttons use
Before
After
=> fix: disable FORCE_MOVE toggle when printing / not ready

src/App.vue, vue.config.js
Closes: #406
Hi, I think the changes are self-explaining. 
Here is a demo video:
https://user-images.githubusercontent.com/44060099/179393694-a09d7429-03a4-4e2a-86b5-5c5831f70527.mp4
=> feat: match theme-color with primary-color

package-lock.json, package.json
We use [@0x4447/potato](https://www.npmjs.com/package/@0x4447/potato) to publish the compiled files to AWS, however this package is old and I believe deprecated as the author deleted the source repo for it...
It's old and it is "polluting" the other dependencies we have, but it is not maintained anymore so there is no way of updating it!
Ideally, we should move away from it ASAP, but for now I am just removing it from the development dependencies and just using it directly via `npx` instead.
=> chore: removes @0x4447/potato from devdependencies

src/components/common/ManualProbeDialog.vue, src/components/settings/ToolheadSettings.vue, src/components/ui/AppBtnCollapseGroup.vue, src/components/ui/AppBtnGroup.vue, src/components/widgets/bedmesh/BedMeshControls.vue, src/components/widgets/toolhead/ToolheadCard.vue, src/globals.ts, src/locales/en.yaml, src/mixins/toolhead.ts, src/store/config/index.ts, src/store/config/types.ts, src/store/printer/getters.ts, src/store/printer/index.ts
Will show buttons for all the "Z Adjust values" from settings + `1` and `0.1` in case they are not there as this might need more broad changes.
There's a new "Show Manual Probe dialog automatically" setting that will automatically open the dialog if we are on the Dashboard or Tune page and a Manual Probe command is initiated.
Dialog:
Button added to dashboard page (only visible when a Manual Probe command is running):
Button added to tune page (only visible when a Manual Probe command is running):
Fixes #761
Fixes #782
=> feat: adds new Manual Probe helper dialog

src/store/gcodePreview/index.ts
=> fix: show current layer in Gcode preview by default

src/components/layout/AppNavDrawer.vue
When we are on Settings page and moonraker restarts (or socket gets closed) we get the "reconnect" buttons, but sub-navigation is still visible.
Before:
After:
=> fix: hide sub-navigation if socket not connected

src/components/widgets/filesystem/setupMonaco.ts
I just realized that moonraker also allows for `[include ...]` sections, but the codelens link docs was incorrectly pointing to [#include](https://moonraker.readthedocs.io/en/latest/configuration/#include) when it should be [#include-directives](https://moonraker.readthedocs.io/en/latest/configuration/#include-directives)
=> fix: corrects moonraker docs link for "include" section

src/components/widgets/bedmesh/BedMeshCard.vue, src/views/Dashboard.vue
Only shows the bed_mesh card if bed_mesh is available and klipper is ready (important for the dashboard card).
=> fix: Check Bed_Mesh Support

src/globals.ts
This should be enough to allow for "save and restart" functionality when editing the "crowsnest.conf" file.
=> feat: Adds minimum support for crowsnest service

src/App.vue, vue.config.js
Mitigates the following warning:
From my tests with Edge and Chrome on Windows 11, it seems to work fine with the value back in!
This is a follow up on this discussion: https://github.com/fluidd-core/fluidd/pull/774#discussion_r932142733
=> fix: mitigates console warning

src/components/common/BedScrewsAdjustDialog.vue, src/components/common/ManualProbeDialog.vue, src/components/settings/ToolheadSettings.vue, src/components/widgets/toolhead/ToolheadCard.vue, src/locales/en.yaml, src/mixins/toolhead.ts, src/store/config/index.ts, src/store/config/types.ts, src/store/printer/getters.ts, src/store/printer/index.ts
UX probably can and should be improved, this is the best I could come up with...
The progress just above the buttons represents the `accepted screws / total screws`
Fixes #792 
=> feat: adds new Bed Screws Adjust helper dialog

src/components/ui/AppChart.vue, src/components/widgets/bedmesh/BedMeshChart.vue, src/components/widgets/thermals/ThermalChart.vue
Fixes the issue where the (thermals and others) chart wouldn't be sized properly after resizing the window or switching from the settings page to the dashboard.
Before
After
=> fix: Enable vue-echarts auto-resizing

src/components/ui/AppMacroBtn.vue, src/components/ui/AppNamedInput.vue, src/components/ui/AppSlider.vue, src/components/ui/AppSwitch.vue, src/components/widgets/console/Console.vue, src/components/widgets/console/ConsoleCommand.vue, src/components/widgets/outputs/OutputFan.vue, src/components/widgets/toolhead/ZHeightAdjust.vue
Current behavior:
- macro buttons only disable when printing (if set as such)
- console controls are always enabled
- labels are always "foreground" text
This changes that to ensure that these controls are disabled if Klipper is down.
=> fix: disable dashboard controls if Klipper is not ready

src/components/widgets/gcode-preview/GcodePreview.vue
If a printer is not configured to have a (0,0) (xmin, ymin) coordinate, the GCode preview currently does not show up like in the picture below. For example, my printer's x goes from -113 to +113 and y from -74 to +74.
I fixed two issues with the SVG generation:
- The final 2 parameters of [`viewBox`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox) are the width & height of the image, not the +x and +y values.
- When flipping the image, the min & max coordinates should be added instead of subtracted. Imagine the print bed has minimum x 100 and maximum x 200. When flipped across the origin, it's going to end up far away and need to be translated 300px back.
Now, the preview shows up:
Signed-off-by: Ryan Adolf ryanadolf123@gmail.com
=> fix: Correct SVG transformations in GCode Preview

src/components/widgets/toolhead/ToolheadMoves.vue, src/components/widgets/toolhead/ToolheadPosition.vue
Send `ACCEL` parameter with `FORCE_MOVE` commands.
For X and Y it will use the currently set acceleration, for Z it will take the `max_z_accel` from the printer configuration
Fixes #814
=> fix: adds ACCEL parameter to FORCE_MOVE commands

src/components/widgets/filesystem/FileSystem.vue, src/store/files/types.ts
Moonraker now has the ability to send the [chamber temperature](https://github.com/Arksine/moonraker/pull/480) as part of the gcode files metadata, so this PR will ensure we send an `M141` command (reference [here](https://marlinfw.org/docs/gcode/M141.html)) if the value is present.
Users that actually want to take advantage of this new feature will need to:
- indicate on their slicer of choice what temperature to set the chamber to.
- create a user macro in Klipper for `M141` (there is no default, so must be created for this to work)
=> feat: preheat printer chamber if value provided

src/components/widgets/gcode-preview/GcodePreview.vue
Delta gcode preview has a bug caused by the changes on #816 
Before #816:
Current:
With the changes on this PR:
=> fix: delta viewbox regression

src/views/Dashboard.vue
Fixes edge case caused by usage of `Object.values`, where containers are retrieved in non-ascending order.
This is because `Object.values` will iterate the object properties by creation order, not alphabetical, so there is the possibility that "container2" could be returned before "container1".
I've noticed that this was happening with the following repro steps:
- start with a new Moonraker database (or delete existing one)
- open Fluidd
- collapse one of the cards on the right column (for example, the temperatures one)
- refresh the page and observe (columns will be switched left and right)
This PR fixes the issue observed with the above steps.
=> fix: edge case where containers order is incorrect

src/App.vue, src/router/index.ts, src/store/config/index.ts, src/store/config/mutations.ts, src/store/config/types.ts, src/views/Dashboard.vue
Moves "width constraint" code back to root container as the changes from #820 caused a misalignment when other elements are visible.
=> fix: width constraint at root container level

src/store/files/actions.ts
Reset G-code Preview state if the file changed is the same as the one being previewed.
Fixes #831 
=> fix: reset G-code Preview state on file overwrite

src/components/widgets/filesystem/FileSystem.vue, src/components/widgets/filesystem/FileSystemBrowser.vue, src/locales/en.yaml, src/store/config/index.ts
Adds new optional Chamber Temp column (defaults to hidden) to the "gcodes" root.
=> feat: add optional Chamber Temp column to jobs

src/store/layout/mutations.ts
While testing, I've found a bug that I believe to have been introduced with the changes of #793.
Repro steps:
- start with fresh (non-existing) moonraker database
- open Fluidd
- collapse Thermals card
- refresh page (F5)
- observe browser developer console
=> fix: ensures containers exist

src/components/widgets/filesystem/FileSystem.vue, src/views/Timelapse.vue
Seems to me we can go without that `timelapseProperty` just by checking the root (as we do for others)
=> refactor: timelapseBrowser property in FileSystem

src/init.ts
Fixes bug introduced by #839: if Moonraker is down, Fluidd will not load (blank page is shown)
=> fix: dispatch even if database creation fails

public/config.json, server/config.json, src/init.ts, src/util/__tests__/sanitize-endpoint.spec.ts, src/util/sanitize-endpoint.ts
Enabling the use of the config.json to allow for a default list of endpoints to be populated on first load of the Fluidd interface.
Signed-off-by: Chris Owen <Chris@ChrisOwen.org>
=> feat: Enabling default list of endpoints via config

docs/customize/themes.md
Not sure if this covers everything yet, LMK if something needs to be changed! :)
Probably would be a good idea to add some kind of README and maybe even an example theme to the themes repo, but I don't have anything ready for that yet.
=> docs: add custom theming documentation

src/components/widgets/diagnostics/StateExplorer.vue
Before, the production build would apply the `vue-json-viewer` styles _after_ the component styles, rendering the component styles useless (this didn't happen in the dev build). This is the easiest way to solve this without changing any of the bundling logic I think.
| Before | After
| --- | --- |
| ![image](https://user-images.githubusercontent.com/25269274/187047879-d550cbba-8fb0-4519-bfac-1cb8ada6e9be.png) | ![image](https://user-images.githubusercontent.com/25269274/187047832-beaa1912-9627-49e2-9881-868a4eaca5e6.png) |
=> fix(diagnostics): Metrics Explorer styling

src/store/cameras/types.ts, src/store/webcams/types.ts
Just limiting the options for camera rotation, matching the validation that Moonraker does on the Webcam API.
=> refactor: webcam related typings

src/components/widgets/bedmesh/BedMeshCard.vue, src/components/widgets/bedmesh/BedMeshChart.vue, src/vue-echarts-chunk.ts
Variance will show directly on the chart on all views (I see no reason why not to show it on the Tune as there is enough space for the value on the chart)
Fixes #853 
=> feat: adds variance to bed mesh chart

src/components/widgets/toolhead/ToolheadMoves.vue, src/components/widgets/toolhead/ToolheadPosition.vue, src/mixins/toolhead.ts
If a `stepper_k1` is found on the configuration, then we will disable the controls for that K axis when Force Move mode is enabled.
Here's an example where `stepper_z1` exists in the printer configuration, and as such we disabled both the Z axis controls and the Z position textbox:
This PR also fixed some minor issues where the wrong axis were being checked!
Fixes #856 
=> fix: disable force_move on axis with multiple steppers

src/components/widgets/limits/PrinterLimits.vue, src/components/widgets/toolhead/PressureAdvanceAdjust.vue
Fixes Pressure Advance units, as it is measures in `mm/(mm/s)` which can be simplified just to `s` (though missing a bit of the significance)
For the [Klipper docs](https://www.klipper3d.org/Config_Reference.html#extruder):
Also changes presentation of acceleration values.
=> fix: pressure advance and acceleration units

src/components/widgets/camera/CameraItem.vue
This is a quick fix for #778 that just sets the iframes width to a static 100%.
It's not optimal, so I am planning to rewrite the sizing logic for iframes for the next minor release (have it dynamically scale based on the container so it automatically matches the rest of the displayed cameras) and I'm therefore leaving #778 open. This  would be a breaking change, so I am not including it in this patch.
This also fixes the size of the iframe in full screen mode, making it cover the entire contentbox.
Before
After
=> fix: Camera iframe width

src/components/common/CollapsableCard.vue, src/components/layout/AppBar.vue, src/components/widgets/filesystem/FileSystemContextMenu.vue, src/locales/de.yaml, src/locales/en.yaml, src/store/layout/actions.ts, src/store/layout/getters.ts, src/views/Dashboard.vue
Creates user and device specific layouts on layout change (based on concatenation of `dashboard-{user}-{device-size}`, clones current `dashboard` if no custom one exists yet).
Allows the overriding of the default layout for new users (or other devices), which can also be reset to the initial state.
Not 100% sure about the placement and usage of header buttons here, but it's what was there before:
Closes #370
Closes #410
=> feat: user/device specific layouts

src/store/auth/actions.ts
Though this seemed to not cause any bug, I found that in a specific place on the code a call to `setCurrentUser` action was passing a single string (username) instead of an object (that should contain username property), so this just fixes that particular issue.
=> fix: auth/setCurrentUser expects object

src/components/widgets/toolhead/ZHeightAdjust.vue
If there is no `stepper_z` in the config, we can't call `Z_OFFSET_APPLY_ENDSTOP`, so just assume we are using a probe and call `Z_OFFSET_APPLY_PROBE` instead.
Fixes #889 
=> fix: check stepper_z exists before applying z_offset

src/components/widgets/gcode-preview/GcodePreviewCard.vue
This fixes an issue where the GCodePreviewCard has a slider to select the current layer, and that start at 1, but the backend `currentLayer` starts at 0, however the `setCurrentLayer` was incorrectly checking for `> 0`, so we could never select the initial layer.
The `currentLayerHeight` needs to be based on the actual current layer and not on the previous one as that could be from a different object on a multi-print and thus show the incorrect value.
I also removed `visibleLayer` getter as it is not in use anywhere.
=> fix: allow initial layer in GcodePreviewCard

src/components/widgets/bedmesh/BedMeshCard.vue, src/components/widgets/console/ConsoleCard.vue, src/components/widgets/endstops/EndStopsCard.vue, src/components/widgets/gcode-preview/GcodePreviewCard.vue, src/components/widgets/jobs/JobsCard.vue, src/components/widgets/system/McuCard.vue, src/components/widgets/thermals/TemperatureCard.vue, src/components/widgets/thermals/TemperaturePresetsMenu.vue
Changes are quite subtle and just in terms of making sure that the left-margin on all the buttons is set to 1.
I also changed the full-screen button from small to x-small, making it consistent with the rest of the buttons.
Before:
After:
=> style: consistent margins across all card buttons

.github/workflows/release.yml
Reverts the fixes from #688 as new version of this action has been published that (hopefully) fixes the issues we've been seeing.
=> chore: use latest changelog-reader-action

src/store/console/getters.ts
Not a big deal change, but `GET_POSITION` and `SET_RETRACTION` are provided from Klipper via Moonraker API, so there is no need to add these here.
=> chore: removes duplicate auto-complete entries

src/components/ui/AppColorPicker.vue
Hide color wheel if we only have a white pin configured - no point showing it otherwise!
This also ensures that in the case of single white-pin configured, we show correct color indicator on dashboard (previously it was always black).
Before:
After:
=> feat: single white channel led control

src/components/widgets/status/StatusTab.vue, src/store/printer/getters.ts
Prefer `print_stats.info` object data (if available) as layers information.
This is part of the new Klipper command [SET_PRINT_STATS_INFO](https://www.klipper3d.org/G-Codes.html#set_print_stats_info) that allows slicers to pass information to Klipper (right now, all it allows is to set `current_layer` and `total_layer`)
=> feat: use layer info from print_stats if available

src/components/ui/AppBtnCollapseGroup.vue, src/components/widgets/filesystem/FileSystemContextMenu.vue, src/views/Tune.vue
Disables the following controls if `klipperReady` is false:
- `Print` and `Preheat` on the file context menu
- All the panels in the "Tune" page
=> fix: disable controls if Klipper not ready

src/components/widgets/filesystem/FileSystemContextMenu.vue, src/locales/en.yaml, src/locales/hu.yaml
Removes the "View Thumbnail" button from the UI and replaces it with the functionality to simply click the thumbnail in order to open it in the file previewer.
Maybe the `zoom-in` cursor style is more appropriate here?
Follow-Up for #891
=> style: open fullscreen thumbnails on thumbnail click

src/components/ui/AppMacroBtn.vue, src/components/widgets/macros/Macros.vue
All macro buttons will show the description configured on Klipper as a tooltip:
M117 and M118 (only visible if overrided!) will now only show a single "message" parameter:
=> feat: uses macro description as button tooltip

src/components/widgets/macros/Macros.vue
Moving macro buttons tooltips to the top for consistency purposes (matches the toolhead controls) and also this way the mouse cursor never blocks them!
=> style: move macro tooltips to the top of the buttons

src/components/settings/GcodePreviewSettings.vue, src/components/settings/ToolheadSettings.vue, src/components/settings/cameras/CameraConfigDialog.vue
Replaces static error messages with translations and also ensures these are shown when required.
=> Replaces static error messages with translations

src/components/ui/AppSlider.vue
The AppSlider is animating every time we enter the container page (just go to Dashboard, navigate to another page, then back to Dashboard, and observe the AppSlider controls behavior)
This PR fixes that ensuring the value is set when the slider is created so that the animation does not occur.
=> fix: stop slider animation on navigating to page

src/views/Login.vue
=> fix: show html formatted welcome message

src/components/widgets/toolhead/ExtruderMoves.vue, src/components/widgets/toolhead/Toolhead.vue, src/components/widgets/toolhead/ToolheadCard.vue, src/components/widgets/toolhead/ToolheadMoves.vue, src/components/widgets/toolhead/ToolheadPosition.vue, src/store/config/index.ts, src/store/config/types.ts
Expose the `forceMove`, `extrudeLength` and `extrudeSpeed` state from the store instead of keeping it local on the component.
Also disable force move for Delta printers as we currently only support "stepper[xyz]" (further changes must be done for Delta support)
=> chore: move forceMove, extrudeSpeed, extrudeLength state to store

src/components/common/AddInstanceDialog.vue, src/components/settings/GcodePreviewSettings.vue, src/components/settings/GeneralSettings.vue, src/components/settings/ToolheadSettings.vue, src/components/settings/auth/UserConfigDialog.vue, src/components/settings/auth/UserPasswordDialog.vue, src/components/settings/cameras/CameraConfigDialog.vue, src/components/settings/console/ConsoleFilterDialog.vue, src/components/settings/console/ConsoleSettings.vue, src/components/settings/macros/MacroCategories.vue, src/components/settings/macros/MacroCategoryDialog.vue, src/components/settings/presets/PresetDialog.vue, src/components/settings/timelapse/TimelapseSettings.vue, src/components/settings/timelapse/subsettings/CustomParkPositionSettings.vue, src/components/settings/timelapse/subsettings/ParkExtrudeRetractSettings.vue, src/components/settings/timelapse/subsettings/ToolheadParkingSettings.vue, src/components/settings/timelapse/subsettings/modes/HyperlapseSettings.vue, src/components/ui/AppSlider.vue, src/components/widgets/bedmesh/SaveMeshDialog.vue, src/components/widgets/diagnostics/config/AxesConfigStep.vue, src/components/widgets/diagnostics/config/CardConfigStep.vue, src/components/widgets/diagnostics/config/MetricsConfigStep.vue, src/components/widgets/filesystem/FileNameDialog.vue, src/components/widgets/filesystem/FileSystem.vue, src/components/widgets/outputs/OutputFan.vue, src/components/widgets/thermals/InputTemperature.vue, src/components/widgets/timelapse/TimelapseRenderSettingsDialog.vue, src/components/widgets/toolhead/ExtruderMoves.vue, src/plugins/filters.ts
Adds a new global `Vue.$rules` that contains most of the validation rules we use.
For the remaining rules, I've made sure that these are using property `get`, as it seems that since Vite migration some of these are not reactive and thus, can't read from existing properties.
Fixes #937
=> chore: refactors validation rules

src/components/common/SystemCommands.vue, src/mixins/services.ts, src/store/server/getters.ts, src/store/server/types.ts
Moonraker now provides the instance ids for the Moonraker and Klipper services, so we can restart the correct services when the respective config files change!
Fixes #638 
=> feat: use service names provided by Moonraker

src/locales/en.yaml
=> fix(i18n): adds missing 'start service' translation

src/store/printer/getters.ts
Currently the thermals are grouped by heaters on top, then temperature fan, and finally temperature sensors, but these are unordered inside these groups.
This PR ensures that we still keep the above grouping, and then inside each group we sort by sensor type, and finally name.
Fixes #956 
=> fix: sort temperature sensors by type and name

src/locales/en.yaml
Removes spaces leading commas:
Before
After
=> fix: extrusion estimation spacing

src/components/widgets/toolhead/ExtruderStats.vue, src/components/widgets/toolhead/Toolhead.vue
=> style: alternative alignment for ExtruderStats

src/components/widgets/exclude-objects/ExcludeObjectsDialog.vue
Highlight the current printing part and show the full row as disabled for excluded parts.
=> style: improves ExcludeObjectsDialog states visibility

src/components/widgets/exclude-objects/ExcludeObjects.vue
Difference is mostly visible in the "active" print, as now we also show the containing border in blue.
=> style: improves G-Code Previewer states visibility

src/components/widgets/thermals/TemperatureTargets.vue, src/components/widgets/thermals/ThermalChart.vue, src/store/printer/getters.ts
Show the Temperature Chart legend with pretty names correctly sorted in the same order as the above Temperature List.
Fixes #972 
=> fix: temperature chart legend

src/components/widgets/filesystem/FileEditor.vue
This is another issue was caused by the migration to Vite, where regular variables are not reactive by nature (which actually respects Vue defaults).
Inlining the variable fixes the problem.
Fixes #977
=> fix: ensures CodeLens is not shown if disabled

components.d.ts, src/App.vue, src/components/common/RegisterServiceWorker.vue, src/locales/en.yaml, vite.config.ts
After the first load, Fluidd will be able to run completely offline!
What this means is that even if the host device where Fluidd was installed to goes offline, users will still be able to open Fluidd and connect to Moonraker (assuming it can be reached!)
This is by taking full advantage of the ServiceWorker cache features, so that all files are cached, including the "config.json" file which is the only dynamic file we have (so users can still change values on this file, click "refresh", and Fluidd will use the latest and cache the file for later offline work)
These changes will also improve the loading speed of Fluidd as most of the files required to run it will always be cached in the browser!
On first load, Fluidd will quickly show a flash message indicating that it is ready to run …
=> feat: allow Fluidd to run fully offline

src/components/widgets/filesystem/FileSystem.vue
The source of this problem can be traced to this [open issue in the Vuetify library](https://github.com/vuetifyjs/vuetify/issues/11600), but this only became an issue for us with the changes from #812.
This fix refactors the code to not rely on the Vuetify DataTable filter capability and instead we now filter the items ahead of binding to the DataTable
Fixes #989
=> fix: mitigates Vuetify bug filtering items ahead

src/components/settings/presets/PresetDialog.vue
Ensure we only set validation rules if the fields are enabled in PresetDialog.
Fixes #993 
=> fix: only validate enabled fields in PresetDialog

src/components/layout/AppNotificationMenu.vue
=> fix: sets maximum notifications lines to 5

src/components/layout/AppBar.vue, src/components/layout/AppUploadAndPrintBtn.vue
Use correct icon for "Upload and Print" functionality (using same one as in the popup menu of the Files card).
Fixes #1000 
=> style: make upload & print icon consistent

src/components/settings/GeneralSettings.vue, src/components/widgets/filesystem/FileSystemBrowser.vue, src/locales/en.yaml, src/plugins/filters.ts, src/store/config/state.ts, src/store/config/types.ts, src/util/__tests__/version-string-compare.spec.ts, src/util/version-string-compare.ts
Allows user to select the type of sorting to apply on the file list between Default, Number Prefix sort, or Version sort.
Default is the current implementation, where we just `compare` from `Intl.Collator` for the current locale.
Number Prefix sort will check if the text has a number prefix (digits only) and if so, use that for sorting. When comparing 2 prefixes, if they are the same, then it will fallback to Default sort.
Version sort matches the type of sorting that `ls -v` or `sort -V` would use.
Example of version sorting:
Note: this does not apply to `number` type values, as those will just be compared directly (this includes dates stored as timestamps), so all the numeric values returned by Moonraker (like "filament", "filament width", or even "modified") will just be compared as …
=> feat: allow sorting text by version or prefix number

src/components/widgets/system/SystemOverviewCard.vue, src/locales/de.yaml, src/locales/en.yaml, src/store/server/types.ts
This PR allows the showing of additional information about the distribution.
It also hides elements that are not available
Signed-off-by: Kerim Bilgic <pfusch3d@gmail.com>
=> feat(ui): show content of release_info

src/components/layout/AppUploadAndPrintBtn.vue, src/components/widgets/filesystem/FileSystem.vue, src/components/widgets/filesystem/FileSystemDragOverlay.vue, src/components/widgets/filesystem/FileSystemMenu.vue, src/globals.ts, src/locales/en.yaml, src/mixins/files.ts, src/util/file-system-entry.ts
This PR allow users to drag and drop files and folders and it will upload all of them, maintaining folder relative folder structure.
It also add a new "Upload Folder" option that allow to select and upload a single folder (this is a browser thing, I haven't found a way to allow multiple) maintaining relative folder structure.
Fixes #1014
=> feat: complete folder upload

src/components/widgets/toolhead/ToolheadPosition.vue
Adds live speed to the Tool panel
Using the same style as in the live coordinates, we would just add the live speed to the "Speed" label, as shown on the above image.
Fixes #1018
=> feat: show live speed while printing

src/components/widgets/toolhead/ExtruderStats.vue, src/components/widgets/toolhead/PressureAdvanceAdjust.vue, src/components/widgets/toolhead/Toolhead.vue, src/store/printer/getters.ts, src/store/printer/types.ts
The current Pressure Advance controls work fine when there is an `[extruder]` with a stepper attached, but when we have them separately (by using `[extruder_stepper]` entries), this would just not work as there is no "active extruder stepper" entity)
To fix this, we will now show the existing PA controls for active extruder if it has a stepper attached, and a new separate box with PA controls for each of the separate extruder steppers.
These boxes are collapsible and by default they will load in collapsed state:
(Note: one can easily test this with a Docker container running [docker-klipper-simulavr](https://github.com/pedrolamas/docker-klipper-simulavr), just set the correct "dual stepper extruder" in the printer.cfg)
Fixes #681
=> feat: Pressure Advance per extruder stepper

src/store/gcodePreview/getters.ts
Previously, the gcode viewer did not work if no extrusion moves were defined. This broke the viewer in cases where Klipper was being used on 2d plotters without a Z or extruder.
Signed-off-by: Kieran Eglin <kieran.eglin@gmail.com>
=> feat: Add support for gcode viewing on plotter-style devices

src/components/settings/GcodePreviewSettings.vue, src/components/widgets/gcode-preview/GcodePreviewCard.vue, src/locales/de.yaml, src/locales/en.yaml, src/store/config/state.ts, src/store/config/types.ts
Works toward #934.
Automatic gcode loading works well on computers, but on mobile browsers it can take away control for several seconds, especially on remote connections. This PR adds a new setting to allow different loading behaviours on mobile vs. desktop.
Note: the label text could definitely use an editorial review.
Signed-off-by: Kieran Eglin <kieran.eglin@gmail.com>
=> feat: setting to disable automatic gcode loading on mobile

src/components/widgets/toolhead/ExtruderStepperSync.vue, src/components/widgets/toolhead/ExtruderSteppers.vue, src/globals.ts, src/locales/en.yaml, src/store/printer/getters.ts, src/store/printer/types.ts
When `extruder_stepper` are in use, this will allow to change the currently synced extruder directly from Fluidd interface (sends the `SYNC_EXTRUDER_MOTION` klipper command):
**Note:** retrieving the active extruder is only possible with the very latest Klipper as this feature has been [recently added](https://github.com/Klipper3d/klipper/pull/6033).
=> feat: extruder selection for each extruder stepper

src/components/settings/timelapse/subsettings/CustomParkPositionSettings.vue, src/components/settings/timelapse/subsettings/ToolheadParkingSettings.vue, src/locales/de.yaml, src/locales/en.yaml, src/store/timelapse/types.ts
Adds support for [mainsail-crew/moonraker-timelapse#96](https://github.com/mainsail-crew/moonraker-timelapse/pull/96) by adding X_ONLY and Y_ONLY park position options
=> feat(timelapse): add new park positions

src/components/widgets/toolhead/ExtruderStepperSync.vue, src/components/widgets/toolhead/ExtruderSteppers.vue, src/globals.ts, src/locales/en.yaml, src/store/printer/getters.ts, src/store/printer/types.ts
Adds support to enable/disable individual extruder steppers (only shown with latest Klipper where `stepper_enable` status object is provided)
=> feat: adds support for extruder stepper enable

src/components/settings/ToolheadSettings.vue, src/components/widgets/toolhead/ExtruderMoves.vue, src/mixins/toolhead.ts
Fixes #1032
Updates the `ToolheadSettings` component to respect an extruder's `max_extrude_only_velocity` and `max_extrude_only_distance` when trying to update the default extrusion distance/speed values. Also adds a last-resort speed/distance check on extrusion/retraction commands
Signed-off-by: Kieran Eglin <kieran.eglin@gmail.com>
=> feat: updated tool extrusion settings to respect printer config

src/App.vue, src/components/layout/AppBar.vue, src/components/layout/AppNavDrawer.vue, src/components/layout/AppNotificationMenu.vue, src/components/ui/AppChart.vue, src/components/ui/AppNamedSlider.vue, src/components/ui/AppNavItem.vue, src/components/widgets/bedmesh/BedMeshCard.vue, src/components/widgets/bedmesh/BedMeshChart.vue, src/components/widgets/diagnostics/DiagnosticsCard.vue, src/components/widgets/filesystem/FileEditor.vue, src/components/widgets/filesystem/FileEditorDialog.vue, src/components/widgets/gcode-preview/GcodePreview.vue, src/components/widgets/gcode-preview/GcodePreviewButton.vue, src/components/widgets/gcode-preview/GcodePreviewCard.vue, src/components/widgets/limits/PrinterLimits.vue, src/components/widgets/outputs/OutputFan.vue, src/components/widgets/outputs/OutputLed.vue, src/components/widgets/outputs/OutputPin.vue, src/components/widgets/retract/Retract.vue, src/components/widgets/thermals/TemperatureCard.vue, src/components/widgets/thermals/ThermalChart.vue, src/components/widgets/toolhead/PressureAdvanceAdjust.vue, src/components/widgets/toolhead/SpeedAndFlowAdjust.vue, src/mixins/browser.ts, src/util/is-mobile.ts
Works toward (but does not resolve) #1044
This replaces the often-redefined `isMobile` component getter with a mixin. Since there was previously two mechanisms for detecting mobile (more commonly through viewport size but sometimes through user agent), I've also renamed `isMobile` to better reflect what we're actually checking for.
After this I'll make the change to fully resolve the issue above, but I didn't want to clutter up this PR.
Signed-off-by: Kieran Eglin <kieran.eglin@gmail.com>
=> chore: refactor isMobile to use mixin

src/components/widgets/thermals/TemperatureCard.vue, src/components/widgets/thermals/TemperatureTargets.vue, src/locales/en.yaml, src/store/config/state.ts, src/store/config/types.ts, src/store/printer/getters.ts, src/store/printer/types.ts
Adds gas resistance value to the available sensors.
Related to #1053
=> feat: adds toggle for gas resistance

src/components/widgets/filesystem/FileSystemFilterMenu.vue, src/components/widgets/filesystem/FileSystemToolbar.vue, src/store/files/getters.ts
Allows configuring which filters to show on any FileSystem control directly on the root properties getter (the order will also be maintained)
Fixes #1059
=> feat: adds filters to gcodes and timelapse roots

src/globals.ts, src/plugins/__tests__/filters.spec.ts
As there is no way to use `Date.prototype.toLocaleDateString()` with ISO-8601, we have been using "sv-SE", but apparently this doesn't not handle correctly when we ask to omit the year.
I've checked all the locales I could find and "lt" (Lithuania) matches all the cases I have tested, so let's use that one going forward!
Fixes #1058
=> fix: use Lithuanian "lt" for ISO-8601 formats

src/mixins/files.ts
Fixes a theme loading race condition on setups where FORCE_LOGINS is turned on, resulting in a 401.
Assumes FORCE_LOGINS is enabled when the configuration hasn't been received yet.
=> fix: assume untrusted user before config receival

src/components/widgets/thermals/TemperatureTargets.vue, src/store/printer/getters.ts
Just use any existing config `sensor_type` of these items to check for "bme280" or "htu21d", and if it matches, retrieve the current values for these entries and include as part of the fans and sensors.
=> fix: include extra sensor data on temperature_fan

src/workers/parseGcode.ts
Ideally, all `EXCLUDE_OBJECT_DEFINE` have a `POLYGON` parameter, but a bug in Cura has caused this to not be the case.
This fix ensures we only attempt to show parts with a defined polygon on the G-code Previewer.
Fixes #1068
=> fix: only add parts with defined polygon

src/store/mesh/getters.ts, src/store/mesh/types.ts, src/store/printer/state.ts
Since v1.23.3, the bed mesh profiles are listed directly from the `bed_mesh` status object, however this only works with https://github.com/Klipper3d/klipper/commit/8b0c6fcb089769f70ecbb11cc3793dcd61f445dd or above.
Before v1.23.3, the bed mesh profiles were listed from the printer config entries, so this PR fixes the issue by adding back this "legacy" behavior when the `bed_mesh` status object doesn't have the profiles.
Fixes #1075
=> fix: add legacy bed mesh profiles from config

components.d.ts, src/components/widgets/filesystem/FileSystem.vue, src/components/widgets/filesystem/FileSystemAddMenu.vue, src/components/widgets/filesystem/FileSystemBulkActions.vue, src/components/widgets/filesystem/FileSystemGoToFileDialog.vue, src/components/widgets/filesystem/FileSystemToolbar.vue, src/locales/en.yaml, src/mixins/state.ts
Adds a new "Go To File" dialog that allow listing and searching all the files in a single root.
A virtual scroll is in use so one can quickly scroll through all the files at once!
Resolves #976
=> feat: adds Go To File dialog

src/components/widgets/filesystem/FileSystem.vue, src/components/widgets/filesystem/FileSystemBrowser.vue, src/components/widgets/filesystem/FileSystemContextMenu.vue, src/components/widgets/filesystem/FileSystemFilterMenu.vue, src/components/widgets/filesystem/FileSystemGoToFileDialog.vue, src/components/widgets/history/JobHistory.vue, src/components/widgets/status/ReprintTab.vue, src/components/widgets/status/StatusTab.vue, src/mixins/files.ts, src/store/config/getters.ts, src/store/config/types.ts, src/store/files/actions.ts, src/store/files/getters.ts, src/store/files/mutations.ts, src/store/files/state.ts, src/store/files/types.ts, src/store/history/actions.ts, src/util/get-file-paths.ts, src/util/merge-file-update.ts
This is a big refactor of the way the file system is managed by Fluidd.
There are a couple of reasons for this refactor:
- store only keeps the raw data we received from moonraker
- do not store history with files in store and instead retrieve that in getters
- provide timelapse files metadata directly in store getters
- make timelapse file operations (move/delete) more constrained
- allow thumbnails in all roots (and not just on "gcodes")
- remove the need to refresh "gcodes" when we store the history state
- ...
I've been writing and testing these changes for a few weeks now and I believe them to be stable.
Assuming this is all working fine, the only downside to it is that we now do some work in the file getters that previously was done only once and stored that in state, but I did not …
=> refactor: file system improvements

src/components/widgets/toolhead/ToolheadCard.vue
We currently disable the `LOAD_FILAMENT`, `UNLOAD_FILAMENT`, `M701` and `M702` if the extruder temperature is not above `min_extrude_temp`.
But some users have code on these macros to raise the extruder temperature before it performs any extruder movement, thus it makes sense to keep these options enabled.
So per macro, if we add a `ignore_min_extrude_temp` variable and set that to `true`, then we will not disable the tool in case that.
Here's a configuration example for this variable:
```ini
[gcode_macro LOAD_FILAMENT]
variable_ignore_min_extrude_temp: True
gcode:
...
```
Fixes #1095
=> fix: allow ignoring min_extrude_temp for load/unload filament macros

src/components/settings/FileEditorSettings.vue, src/components/widgets/filesystem/FileEditor.vue, src/components/widgets/filesystem/FileEditorDialog.vue, src/components/widgets/filesystem/FileSystem.vue, src/locales/en.yaml, src/store/config/state.ts, src/store/config/types.ts, src/store/files/getters.ts, src/util/md5-as-base64.ts
This PR adds a new Monaco Editor option to "Save and restore view state" (defaults to enabled)
With this option enabled, any file that the user opens will have the current view state (scroll position, selected areas, folds/unfolded regions, ...) stored in the browser local storage when the user closes the editor, and restored when the user re-opens the file.
https://github.com/fluidd-core/fluidd/assets/85504/872b5f70-4632-47bc-ace3-6ac30b9f85a6
To ensure there are no collisions between multi-instances, roots, paths, and filenames, this is the process to generate the state key:
- Create the "get file" Moonraker API URL (so that will be `<moonraker_base_url>/server/files/<root>/<path>/<filename>`)
- Generate an MD5 of this url and encode in Base64 (makes a smaller string)
- Prepend …
=> feat: save and restore editor view state

src/components/widgets/filesystem/FileSystem.vue, src/components/widgets/gcode-preview/GcodePreviewCard.vue, src/mixins/files.ts
Do not show gcode load dialog if operation has been cancelled.
Fixes #1127
=> fix: don't show gcode load dialog if canceled

src/components/widgets/camera/CameraItem.vue, src/components/widgets/camera/services/HlsstreamCamera.vue, src/components/widgets/camera/services/IframeCamera.vue, src/components/widgets/camera/services/IpstreamCamera.vue, src/components/widgets/camera/services/MjpegstreamerAdaptiveCamera.vue, src/components/widgets/camera/services/MjpegstreamerCamera.vue, src/components/widgets/camera/services/WebrtcCamerastreamerCamera.vue, src/dynamicImports.ts, src/mixins/camera.ts
This refactor will break CameraItem component that currently handles all camera types into separate components for each camera type.
There are a few advantages with this, specifically:
- load the camera dynamically using Vite infrastructure (thus reducing the bundle size)
- split concerns per stream service type
- easier to add new stream services
=> refactor: move each camera to its own component

src/mixins/camera.ts
During the camera refactor work, a bug was introduced where the relative camera URL would use the API origin as base when in fact it should be using the current browsing document origin (as it was before)
This PR reverts to the old (correct) behavior.
Fixes #1144
=> fix: use current origin for relative camera URLs

src/components/widgets/spoolman/SpoolSelectionDialog.vue
Adds a new "Material" column to the Spoolman selection dialog.
Resolves #1143
=> feat: add material type column to Spoolman dialog

docs/features/spoolman.md, src/components/settings/SpoolmanSettings.vue, src/components/widgets/camera/CameraItem.vue, src/components/widgets/camera/services/DeviceCamera.vue, src/components/widgets/spoolman/QRReader.vue, src/components/widgets/spoolman/SpoolSelectionDialog.vue, src/locales/de.yaml, src/locales/en.yaml, src/store/cameras/types.ts, src/store/config/state.ts, src/store/config/types.ts
As described in https://github.com/fluidd-core/fluidd/pull/1119
Adds support for spoolman QR codes (https://github.com/Donkie/Spoolman/issues/10).
Adds an option to automatically commit a spool selection when a valid QR code is scanned (no need to manually confirm the selection)
Adds support for using the device's camera as a scan source (https://github.com/fluidd-core/fluidd/pull/1119#issuecomment-1676159359)
Closes https://github.com/fluidd-core/fluidd/issues/1151
=> feat(spoolman): QR code scanning support

src/mixins/camera.ts
When changing between two cameras of the same type, the control is reused and as such, playback is never reset (so it keeps using the previous camera URLs)
This PR fixes it by monitoring the `camera` property and ensuring that playback is reset when it changes.
Fixes #1158
=> fix: reset camera on change

src/locales/de.yaml
just fixed a small typo in the german translation of the Spoolman widget
=> fix(i18n-DE): Fix typo in german translation

src/locales/pl.yaml
- Changed "Gospodarz (host)" to "host" because it is more appropriate.
- Corrected the translations of "commits" from "zmiany (changes)" to "zatwierdzenia (commits)"
=> feat(i18n-PL): update Polish translations

src/components/widgets/thermals/TemperatureCard.vue, src/components/widgets/thermals/TemperatureTargets.vue, src/components/widgets/thermals/ThermalChart.vue, src/store/chart_helpers.ts, src/store/charts/actions.ts
We currently take the Klipper section name and use only the component name (as in the second part of said section name) as key to the thermal storage, but that is becoming a problem when we have a `[extruder]` and `[tmc2240 extruder]` as these will both have "extruder" as key.
This PR fixes this issue by using the full section name as key.
Note: the thermal chart will still show two Extruder entries! We probably can and should improve this, but I will leave that for a different PR.
Fixes #1166
=> fix: use full Klipper key for thermal data storage

src/components/widgets/toolhead/ToolheadMoves.vue
Delta printers can only home all axis at the same time, but currently we show "Home XY" button when we should be showing "Home All" button.
Fixes #1174
=> fix: delta printers can only home all

src/globals.ts, src/store/files/actions.ts, src/store/files/types.ts, src/util/get-file-paths.ts
Moonraker currently sends websocket notifications for file system changes on ".git" folders, causing Fluidd to refresh the File System cache.
This PR will check if a ".git" folder is part of the path in the notification, and if so, ignore it.
Fixes #1193
=> fix: ensures .git folders are excluded

src/components/widgets/filesystem/FileSystem.vue, src/components/widgets/filesystem/FileSystemBrowser.vue, src/components/widgets/gcode-preview/GcodePreviewCard.vue, src/components/widgets/job-queue/JobQueue.vue, src/locales/en.yaml
Improves drag & drop support by:
- adds `text/html`, `text/plain` and `text/uri-list` data types
- allows loading of gcode files in the Gcode Previewer via drag & drop
- refactored (simplified) the multi-selection code
Resolves #1202
=> feat: improve drag & drop support

src/components/common/AddInstanceDialog.vue, src/plugins/filters.ts
Adds support for Moonraker new `route_prefix` setting, where a user can specify a subpath for the server such as "moonraker/printer1"
Resolves #1203
=> feat: adds moonraker "route_prefix" support

src/components/widgets/job-queue/JobQueue.vue, src/components/widgets/job-queue/JobQueueBulkActions.vue, src/components/widgets/job-queue/JobQueueContextMenu.vue, src/components/widgets/job-queue/JobQueueMultiplyJobDialog.vue, src/locales/en.yaml
Adds a new Multiply context menu item (and bulk item selection toolbar action) that allows to enqueue multiple copies of the same queued job.
Resolves #1212
=> feat: adds Multiply context menu item to Job Queue

src/components/layout/AppBar.vue, src/components/settings/FileEditorSettings.vue, src/components/settings/GeneralSettings.vue, src/locales/af.yaml, src/locales/de.yaml, src/locales/en.yaml, src/locales/hu.yaml, src/locales/pl.yaml, src/locales/ru.yaml, src/locales/zh-CN.yaml, src/store/config/state.ts, src/store/config/types.ts, src/util/is-key-of.ts
Replaces the existing "Ignore default bed mesh Pending Configuration Changes" boolean setting with a new configurable "Sections to ignore Pending Configuration Changes" combo setting.
It defaults to an empty list, but when clicked it will provide two items that can be easily added by clicking on them.
Besides those items, users will be able to add whatever they want to the list.
Any pending configuration changes on these sections will just be ignored and will NOT cause the "Save Config & Restart" button to show (unless some other section that is not also on this list also has pending changes).
Resolves #1210
=> feat: ignore pending config changes in custom sections

src/components/settings/GeneralSettings.vue, src/globals.ts, src/plugins/filters.ts
We currently use Lithuanian for ISO 8601 date & time formatting as that is the closest match to it.
Given that, a bug was introduced when we mix ISO with non-ISO date & time formats, where a full datetime would always be formatted in Lithuanian.
To mitigate this issue, when the user has selected to mix ISO with non-ISO formats, we will format each part separately and join the results (separated by a simple space).
Fixes #1220
=> fix: mixed ISO / non-ISO date & time formats

src/components/settings/GcodePreviewSettings.vue, src/components/widgets/gcode-preview/GcodePreview.vue, src/locales/en.yaml, src/store/config/state.ts, src/store/config/types.ts
Adds a simple origin indicator to the G-Code Previewer
The color scheme follows what Cura and PrusaSlicer use, so it is red for X, green for Y and blue for Z (which in our case, is just a dot on the 0, 0 coordinate)
Resolves #1226
=> feat: adds origin to GcodePreview

src/components/layout/AppNavDrawer.vue
Adds some padding to the bottom of the navigation bar on mobile view to ensure that the floating Emergency Button doesn't stop users from accessing the navigation options.
Fixes #1231
=> fix(style): pad navigation drawer bottom on mobile view 

src/components/widgets/bedmesh/BedMeshCard.vue, src/components/widgets/bedmesh/BedMeshChart.vue, src/util/transform-mesh.ts
Corrects the order or e-charts dimensions.
Tested with sample config:
```ini
[bed_mesh]
speed = 400
mesh_min = 5,5
mesh_max = 225,182
probe_count = 5, 4
[bed_mesh default]
version = 1
points = 
-0.016250, -0.010833, 0.001667, 0.004167, 0.047500
0.035000, 0.023750, 0.018750, -0.015000, 0.046667
0.020417, 0.002083, 0.027500, 0.007500, 0.039167
-0.000833, -0.030000, -0.028333, -0.019583, 0.008333
tension = 0.2
min_x = 5.0
algo = lagrange
y_count = 4
mesh_y_pps = 2
min_y = 5.0
x_count = 5
max_y = 182.0
mesh_x_pps = 2
max_x = 225.0
```
Results:
Introduced by fb9a46ce0de9ef465a3a8127673e092fdae10c2c
Fixes #1234
=> fix: corrects order of e-charts dimensions

src/components/widgets/bedmesh/BedMeshChart.vue
We currently use the Bed Mesh rectangle as the limits for the preview.
This changes that behavior to ensure we show the Bed Mesh preview using the full configured bed dimensions.
On both examples above, the bed size is 235x235 yet on the top we are not using the full bed dimensions but the mesh dimensions.
Resolves: #1243
=> feat: use full bed dimensions on bed mesh preview

src/components/widgets/console/ConsoleItem.vue
=> fix: disable console timestamps text wrap

src/components/widgets/toolhead/ToolChangeCommands.vue
Adds support for the `Tx` macros `variable_active` so that the active tool is highlighted.
Resolves #1261
=> feat: highlight active tool

components.d.ts, src/App.vue, src/components/common/ActionCommandPromptDialog.vue, src/store/console/actions.ts, src/store/console/mutations.ts, src/store/console/state.ts, src/store/console/types.ts
Adds support to the prompt dialog commands, based on [Octoprint Action Command Prompt](https://docs.octoprint.org/en/master/bundledplugins/action_command_prompt.html).
This feature was requested [here](https://github.com/mainsail-crew/mainsail/pull/1630), and after discussion with Mainsail devs, we have come to an agreement for an MVP.
The implementation here matches the documentation [here](https://docs.mainsail.xyz/~/changes/WqGAJH0GaI5torSkb3GO/overview/features/macro-prompts), with the exception of `action:prompt_button_group_*` (these are for now ignored and we just stack all the buttons).
Commands:
```
RESPOND TYPE=command MSG="action:prompt_begin MacroPrompt"
RESPOND TYPE=command MSG="action:prompt_text These are all button colors"
RESPOND TYPE=command MSG="action:prompt_button …
```
=> feat: adds Prompt Dialog support

src/components/widgets/camera/services/WebrtcGo2RtcCamera.vue, src/components/widgets/toolhead/ToolheadControlCircle.vue
fix: add attribution and inspiration for the source circle control was adapted from. This was already in the original PR, making it more obvious by moving out the top. 
Signed-off-by: vajonam <152501+vajonam@users.noreply.github.com>
=> fix: corrects original source attributions

src/components/settings/GcodePreviewSettings.vue, src/locales/de.yaml, src/locales/en.yaml, src/store/config/state.ts, src/store/config/types.ts, src/store/gcodePreview/actions.ts
Adds a config option to disable displaying part bounding boxes in the Gcode viewer if there's only a single part
Closes https://github.com/fluidd-core/fluidd/issues/1308
=> feat(GcodePreview): add option to hide part bounding box when printing a single part

src/components/widgets/system/KlipperLoadChart.vue, src/components/widgets/system/McuLoadChart.vue, src/components/widgets/system/MoonrakerLoadChart.vue, src/components/widgets/system/SystemLoadChart.vue, src/components/widgets/system/SystemMemoryChart.vue, src/locales/en.yaml
As you can see on image below, **load**, **awake time** and **memory used** are not translated. They are fixed string in the code. Changed fixed string with translatable code.
=> i18n: adds translation keys for System Utilization labels

src/api/socketActions.ts, src/components/layout/AppSettingsNav.vue, src/components/settings/ToolheadSettings.vue, src/components/widgets/filesystem/FileSystem.vue, src/components/widgets/spoolman/SpoolmanCard.vue, src/components/widgets/status/PrinterStatusCard.vue, src/locales/de.yaml, src/locales/en.yaml, src/store/socket/actions.ts, src/store/spoolman/actions.ts, src/store/spoolman/getters.ts, src/store/spoolman/mutations.ts, src/store/spoolman/state.ts, src/store/spoolman/types.ts, src/views/Dashboard.vue, src/views/Settings.vue
Adds support for the v2 responses and events proposed in https://github.com/Arksine/moonraker/pull/792
Emits errors via toast notifications (on initial load) and shows a disconnected/out-of-sync state more clearly:
=> feat(spoolman): handle v2 responses, improve connection error handling

src/store/auth/actions.ts
Ensures we do not send an `Authorization` header to the `/access/login` and `/access/refresh_jwt` Moonraker endpoints.
Fixes #1320
=> fix: ignore Authorization on login or token refresh

src/components/widgets/camera/services/MjpegstreamerAdaptiveCamera.vue
Resolves an error when destroying an adaptive MJPEG camera feed:
Profiling showed this also improves `handleRefresh` performance by ~15% (1.97ms vs 1.67ms).
=> refactor(cameras): use cached url object for adaptive MJPEG sources

src/mixins/files.ts, src/util/file-system-entry.ts
Main issue here is that some helper methods sometimes returned a "\" terminated path, which would then lead to these weird differences.
I made sure that these methods do not return a terminated "/"
Fixes #1325
=> fix: file path on upload

src/components/widgets/filesystem/FileSystem.vue, src/components/widgets/filesystem/FileSystemFilterMenu.vue, src/locales/en.yaml, src/store/files/getters.ts, src/store/files/types.ts
Adds a filter for crowsnest backup files:
=> feat(FileSystem): add crowsnest backup file filter

src/components/settings/VersionSettings.vue
Resolves a console warning when multiple update sources have active warnings:
=> fix: console warning when multiple update sources have warnings

src/components/settings/VersionSettings.vue
Adds a link to components in the Software Updates panel. When clicked, it will open the repository URL on a new separate browser window/tab.
On hover, a tooltip with the URL is shown.
Resolves #1313
=> feat: adds link to components in software updates

src/components/widgets/spoolman/SpoolSelectionDialog.vue
Adds missing Vue.js expression brackets.
Fixes #1351
=> fix(spoolman): dialog title

src/store/macros/getters.ts
> When a macro is edited via the UI it saves a copy of it in the database, which is then used to override some default settings. It looks like this also overrides the macros variables, so they will never change as far as the UI is concerned.
Fixes #1269 not showing up
=> fix: don't override `gcode_macro` variables with stale values

src/store/macros/getters.ts, src/store/macros/mutations.ts
Follow-up on https://github.com/fluidd-core/fluidd/pull/1355
=> fix: remove redundant data from stored macros

src/components/widgets/bedmesh/BedMeshChart.vue, src/components/widgets/diagnostics/DiagnosticsCard.vue, src/components/widgets/thermals/ThermalChart.vue, src/store/charts/getters.ts
By default, e-charts uses "Microsoft YaHei" in Windows platform and "sans-serif" otherwise.
This makes sure we use "Roboto" by default on our existing charts.
I've also ensured that we use "startcase" format on the tooltip labels.
Fixes #1352
=> style: use Roboto font family in charts

src/components/widgets/toolhead/ToolheadCard.vue, src/globals.ts
=> feat: adds probe accuracy support

package-lock.json, package.json, src/components/widgets/exclude-objects/ExcludeObjects.vue, src/main.ts
To fix the tap issues, we are now introducing the vue2-touch-events library.
This will deprecate #1363
Fixes #1359
=> refactor: uses vue2-touch-events for tap

src/components/widgets/bedmesh/BedMeshChart.vue
Improves visibility of text in the bed mesh chart and makes it consistent with the rest of the charts in use.
Fixes #1369
=> fix(style): text color on bed mesh chart

package-lock.json, package.json, src/components/widgets/filesystem/FilePreviewDialog.vue, src/components/widgets/filesystem/FileSystem.vue, src/globals.ts, src/store/config/state.ts, src/store/files/getters.ts
Allows viewing of rendered Markdown (*.md and *.markdown) files.
Resolves #656
=> feat: view rendered Markdown files

src/components/settings/ThemeSettings.vue, src/components/settings/macros/MacroSettingsDialog.vue, src/components/ui/AppColorPicker.vue, src/components/ui/AppIroColorPicker.vue, src/components/widgets/diagnostics/config/MetricsConfigStep.vue, src/components/widgets/outputs/OutputLed.vue, src/store/diagnostics/types.ts, src/store/layout/actions.ts, src/store/layout/mutations.ts, src/store/layout/state.ts
This PR refactors the `AppIroColorPicker` and `AppColorPicker` to use v-model and propsync where possible, thus making the control easier to consume, and fixing the reported issue.
Note: following up on what we already do with our custom input controls, changing the value on the text input boxes will not take effect unless <kbd>Enter</kbd> is pressed.
Fixes #1372
=> fix: make color picker use v-model and propsync

src/components/widgets/filesystem/FilePreviewDialog.vue
Fixes a console error when opening a file preview dialog that doesn't have a base path supplied:
=> fix(FilePreviewDialog): make `path` property optional

src/components/widgets/system/SystemOverviewCard.vue
If the `release_name` starts with "#", we will then use the `release_id` as correct name - this is a specific fix for Armbian distro but should not be a problem for other distros.
Fixes #1385
=> fix: Armbian distribution information

src/components/common/AddInstanceDialog.vue, src/components/common/PeripheralsDialog.vue, src/components/common/ScrewsTiltAdjustDialog.vue, src/components/settings/auth/UserConfigDialog.vue, src/components/settings/auth/UserPasswordDialog.vue, src/components/settings/cameras/CameraConfigDialog.vue, src/components/settings/console/ConsoleFilterDialog.vue, src/components/settings/macros/MacroSettingsDialog.vue, src/components/settings/presets/PresetDialog.vue, src/components/ui/AppDialog.vue, src/components/ui/AppSetting.vue, src/components/widgets/diagnostics/DiagnosticsCardConfigDialog.vue, src/components/widgets/filesystem/FileSystemToolbar.vue, src/components/widgets/spoolman/SpoolSelectionDialog.vue, src/components/widgets/status/PauseAtLayerDialog.vue, src/components/widgets/system/McuInformationDialog.vue, src/components/widgets/timelapse/TimelapseRenderSettingsDialog.vue
Improves layout in small screens:
- dialogs will be shown in full-screen.
- setting entries will break in 2 lines (title + content)
This will fix the problem with large dialogs (one can now scroll without affecting the background) and dismiss without a button (a close button is now shown on all dialogs).
Before | After
--- | ---
Before | After
--- | ---
Before | After
--- | ---
Before | After
--- | ---
Before | After
--- | ---
Before | After
--- | ---
=> feat: layout improvements for small screen

src/mixins/toolhead.ts
Current conditions disabled extrusion controls on Fluidd if the klipper min_extrude_temp protection is set to a sub-zero temp.
For some context, I'm working on a ceramic printer, that does not have any heater nor thermistor on the hotend. The quick and easy way to disable any temp-related security on klipper is to set min_extrude_temp to -273.15, so that any temp detected by a connected (or in my case disconnected) thermistor won't prevent the extrusion.
While this works as expected with klipper (sending `G1 E10` does extrude), the extrusion controls on fluidd are disabled with this cheeky message: 
Note: I haven't looked at how min_extrude_temp is fetched by fluidd, maybe a value of 0 has a special meaning (i.e. a default value when undefined / could not be fetched?)
=> fix: use Klipper can_extrude by default

src/components/widgets/filesystem/FileSystemBrowser.vue, src/store/config/actions.ts, src/store/config/mutations.ts, src/store/config/state.ts, src/store/config/types.ts
This will store the last user selected file sort order (per root) and restore it on reload of the page.
I also did a small refactor of the initial set of `state.uiSettings` to make it a bit more dynamic (we had already forgotten to add a few properties there, this should ensure that is now automatic)
=> feat(FileSystem): remember last sort order

docs/features/cameras.md, src/components/settings/cameras/CameraConfigDialog.vue, src/components/widgets/camera/services/WebrtcMediamtxCamera.vue, src/locales/de.yaml, src/locales/en.yaml, src/locales/hu.yaml, src/locales/ja.yaml, src/locales/ko.yaml, src/locales/pl.yaml, src/locales/ru.yaml, src/locales/sl.yaml, src/locales/tr.yaml, src/store/webcams/types.ts
Adds support for WebRTC MediaMTX camera.
Testing can be done with Docker!
- Start the container with the following (**change "192.168.20.60" to test machine local IP!**):
```sh
docker run --rm -it -e MTX_PROTOCOLS=tcp -e MTX_WEBRTCADDITIONALHOSTS=192.168.20.60 -p 8554:8554 -p 1935:1935 -p 8888:8888 -p 8889:8889 -p 8890:8890/udp -p 8189:8189/udp bluenviron/mediamtx:latest-ffmpeg
```
- With container running, open http://localhost:8889/mystream/publish
- Select a camera, change settings as required, click "publish"
- In Fluidd, add a new "WebRTC (MediaMTX)" camera, set streaming url to http://localhost:8889/mystream
- Save and test
Resolves #1407
=> feat: adds WebRTC (MediaMTX) support

src/components/widgets/spoolman/SpoolSelectionDialog.vue, src/store/printer/getters.ts
Functional Changes:
- Fixes file metadata retrieval  
(we might want to move this logic into `SocketActions.serverFilesMetadata` to ensure a consistent behavior?)
- Fixes the printer state checks (sanity checks now only run when starting a print or changing the spool while an active print job is running)
Re-ordered some code for a clearer execution path
Closes https://github.com/fluidd-core/fluidd/issues/1408
=> fix(spoolman): improve sanity check logic

src/components/settings/GeneralSettings.vue, src/locales/de.yaml, src/locales/en.yaml, src/locales/tr.yaml, src/store/config/types.ts, src/store/printer/getters.ts
- Restores the filament estimation calculation code
- Allows selection of absolute file position progress (`virtual_sdcard.progress` from Klipper)
- If relative file position progress selected and not available, fallback to `virtual_sdcard.progress`
=> feat: print progress estimation improvements

src/components/widgets/gcode-preview/GcodePreview.vue, src/workers/parseGcode.ts
I've noticed that some files sliced by Orca Slicer have G0/G1 commands without any X, Y, Z, or E change.
Though I am not sure why these commands exist, the fact is that this introduced a bug on the Gcode Previewer, where these moves would cause extra extrusion markers to apper.
The fix here is to ignore any G0/G1/G2/G3 command that does not include at least one of the necessary coordinates change arguments.
This also includes a minor fix for the previewer code where `retractions` where incorrectly being checked for `extrusions`.
=> fix(gcodepreview): ignore moves without coordinates

src/components/ui/AppNamedSwitch.vue, src/components/widgets/outputs/OutputFan.vue, src/components/widgets/outputs/OutputPin.vue, src/store/printer/getters.ts, src/store/printer/types.ts
Ideally, limited scale values in the front-end should be presented as a percentage instead of the Klipper value - that is for config and console purposes.
The changes in this pull request are as follows:
- non-controllable (read-only) fans and output pins will show "Off" when value is 0, otherwise presents the value on a scale of 0% to 100%.
- controllable pwm output-pins will always present the value on a scale of 0% to 100%.
```ini
[heater_fan heater_fan]
pin: PD4
off_below: 0.2
shutdown_speed: 0.0
max_power: 0.6
fan_speed: 0.85
[output_pin test_pwm_pin]
pin: PD7
pwm: True
value: 0.6
scale: 0.8
cycle_time: 0.1
```
=> feat: show all fan and pin values as percentages

src/locales/en.yaml, src/store/printer/getters.ts
When we added support for the TMC2240 stepper drivers back in #1133, these are using the `tmc2240 xxxxxx` for naming, which leads to have "Stepper X" or a 2nd "Extruder" entry on the list, both wrong.
Saying "Stepper X" give the idea that these are the stepper motor temperatures, when in fact these are the stepper motor driver temperatures.
So I propose that we instead show "X Driver" and "Extruder Driver" respectively.
=> feat: use correct stepper temperature label

src/components/layout/AppSettingsNav.vue, src/components/settings/GeneralSettings.vue, src/locales/en.yaml, src/util/file-system-entry.ts, src/util/fluidd-content.ts
Add a new Backup and Restore buttons to easily export and import Fluidd settings across multiple printers.
As a first implementation, this will backup/restore ALL Fluidd settings (there is no selections of specific parts of the settings).
Resolve #1113
=> feat: backup and restore settings

.github/workflows/build.yml, .github/workflows/release.yml, package.json
As discussed over Discord, we need to move the S3 buckets hosting https://app.fluidd.xyz and https://dev-app.fluidd.xyz to a new account.
I took the opportunity to replace the deprecated tool to upload to S3 with a GitHub action that supports a more modern authentication method.
There are a few secrets to be added to the repository settings, which I will share via private message.
Signed-off-by: Rogerio Goncalves <rogerlz@gmail.com>
=> ci: move the deploy to a new account and buckets

.github/workflows/build.yml, .github/workflows/release.yml
The PR [#1433](https://github.com/fluidd-core/fluidd/pull/1433) breaks the Docker image upload due to the permission changes added for the OIDC integration.
As discussed over Discord, this PR moves the permissions to the job level. 
To accommodate this, the release action has been split into two jobs.
Signed-off-by: Rogerio Goncalves <rogerlz@gmail.com>
=> ci: break release workflow into separate jobs

docs/customize/hide_outputs.md, src/store/printer/getters.ts
Automatically hide any temperature sensor (or related item) that starts with "_", just like we already do for macros, output pins and fans.
Resolves #1440
=> feat: hides thermal sensors starting with "_"

src/components/settings/SpoolmanSettings.vue, src/components/widgets/spoolman/SpoolSelectionDialog.vue, src/components/widgets/spoolman/SpoolmanCard.vue, src/locales/de.yaml, src/locales/en.yaml, src/plugins/filters.ts, src/store/config/state.ts, src/store/config/types.ts
Adds a new spoolman setting to select the display unit (weight (g) or length (m)) of the remaining (and total) filament on a spool:
**Weight (default)**
**Length**
---
Closes #1442
=> feat(spoolman): add remaining filament display unit setting

src/components/widgets/filesystem/setupMonaco.ts, src/globals.ts, src/locales/en.yaml, src/store/printer/getters.ts, src/store/server/getters.ts
Checks if we are running on [Danger-Klipper](https://dangerklipper.io) and if so, use its website for documentation.
Note: given the popularity of Klipper, there are now quite a few "flavors" proliferating, but we have **no plans to add indiscriminate support to any of these Klipper forks.**
However, Danger Klipper is now the main Klipper fork and is gaining significant traction, hence why we are specifically adding config support for it here.
Resolves #1349
=> feat: adds Danger Klipper config support

src/store/helpers.ts, src/store/printer/actions.ts
Shows a notification message when any `TMCxxxx` driver reports an `otpw` flag (over-temperature pre warning)
The link on the notification is currently pointing to https://www.klipper3d.org/TMC_Drivers.html#tmc-reports-error-ot1overtemperror
Resolves #1105
=> feat: show warning for Trinamic OTPW flag

src/components/common/PeripheralsDialog.vue, src/components/settings/presets/PresetDialog.vue, src/components/widgets/bedmesh/BedMeshChart.vue, src/components/widgets/camera/CameraItem.vue, src/components/widgets/sensors/Sensors.vue, src/components/widgets/thermals/ThermalChart.vue, src/plugins/filters.ts, src/store/charts/getters.ts, src/store/printer/getters.ts, src/store/server/actions.ts
Fluidd item names/labels format currently removes any non-letter/digit and adds spaces between then, which is incorrect.
The new approach works like this:
- Replace any `_` with ` ` (single space)
- Split string by single space
- Remove any empty entry (resulted from multiple consecutive spaces)
- Capitalize the first letter of each part of the splited string
- Join the result, separating the items with a single space
Fixes #1460
=> fix: item name format and capitalization

src/util/event-helpers.ts
Check for Meta key press (<kbd>Cmd</kbd> key in Mac, <kbd>Win</kbd> key in Windows)
Fixes #1475
=> fix: Check for Meta key on keyboard shortcuts

src/components/widgets/camera/CameraItem.vue
Bug introduced by changes made on #1468.
Reverting the changes on [this line](https://github.com/fluidd-core/fluidd/pull/1468/files#diff-327a303e8a69bc6e708f9fa85b35d49acfbf1dd893fd169bc0dc343e5840af7cL119) fixes the problem.
Fixes #1478
=> fix: Dynamic loading of camera components

src/components/widgets/filesystem/FileSystem.vue
Include `*.log.1`, `*.log.2`, etc. files when filtering out rolled logs.
Resolves #1480
=> feat(FileSystem): Filter KlipperScreen rolled logs

src/components/widgets/macros/MacroBtn.vue
For any `Gn` or `Mn` macro (where `n` is one of more digits), we will not add `=` as a parameter separator as these are considered overrides of classic G-code commands
Resolves #1481
=> fix: don't use separator for gcode macros

src/store/layout/mutations.ts
We have had a few reports from users that Fluidd stops working after editing the dashboard layout.
It seems that somehow the layout data is getting incorrectly recorded in the database with `null` values for some cards.
Though I don't yet know the reason for this happening, the proposed fix here is to filter these `null` values out before we attempt to load the layout.
Fixes #1473
=> fix: null check cards on layout init

src/util/__tests__/gcode-macro-params.spec.ts, src/util/gcode-macro-params.ts
Hide any macro parameter that starts with "_"
=> feat: hides macro parameters starting with "_"

src/components/widgets/toolhead/ExtruderMoves.vue, src/components/widgets/toolhead/ToolheadControlBarsAxis.vue, src/components/widgets/toolhead/ToolheadControlCircle.vue, src/components/widgets/toolhead/ToolheadControlCross.vue, src/components/widgets/toolhead/ToolheadPosition.vue, src/mixins/state.ts
Ensure that when we move the toolhead or extruder, we use the correct absolute/relative move and then restore the previous mode after the move.
=> feat: restore positioning mode after extrude/move

src/App.vue, src/components/ui/AppDragOverlay.vue
The main issue here I believe was with the fact that the overlay would start with `pointer-events` enabled even though we are disabling from the root element via code, so there was a small race condition.
Setting `pointer-events: none` on the overlay styling seems to have solved that problem.
Furthermore, the `dragenter` event seems to work better using the same code as `dragover` so I made both methods use the same handler.
I've tested this on Windows 11 with the Chrome (latest), Firefox (latest) and Edge (latest dev version) and got it working perfectly on all of them.
Fixes #1450
=> fix: hide drag overlay on mouse drag leave

src/router/index.ts
Moonraker provides an authentication feature but has no authorization concept, so when users are authorized as an trusted (anonymous) user, there is no point showing the login page, and thus safe to redirect to main page, which is what this PR fixes.
Fixes #1497
=> fix: redirect from login page if authenticated

src/components/ui/AppNamedSlider.vue, src/components/ui/AppTextField.vue, src/components/widgets/thermals/TemperatureTargets.vue, src/components/widgets/toolhead/ToolheadPosition.vue
Increases the precision of Z from 2 to 3 decimal places.
**Note:** this also changes the current behavior of executing the change on lost-focus to only do it on <kbd>Enter</kbd> key pressed - just like every single other input on the dashboard!
Resolves #1502
=> feat: increase Z precision to 3 decimals

src/components/widgets/filesystem/FileSystem.vue, src/components/widgets/filesystem/FileSystemFilterMenu.vue, src/locales/en.yaml, src/store/files/getters.ts, src/store/files/types.ts
Adds a new optional file system filter for Moonraker temporary upload files (.mru)
Resolves #1503
=> feat(FileSystem): allow filtering Moonraker temp upload files

src/components/widgets/console/ConsoleCommand.vue
Use a single entry to show the auto-complete options, thus making it easier to read.
This also matches the output format we get from `HELP` command, so makes it more "familiar".
=> style(Console): single auto-complete console entry

src/components/widgets/thermals/TemperatureTargets.vue, src/mixins/services.ts, src/store/charts/actions.ts, src/store/charts/mutations.ts, src/store/index.ts, src/store/socket/actions.ts
Ensures we ONLY clear the chart data on reset, and not the whole chart state (that includes the selected sensors and heaters!)
Fixes #1297
=> fix(Charts): allow resetting chart store only

src/components/widgets/filesystem/FileSystem.vue, src/components/widgets/filesystem/FileSystemUploadDialog.vue, src/mixins/files.ts, src/store/files/mutations.ts, src/store/files/types.ts
Adds a `uid` to each upload/download file item so we can more easily track the state in the store.
This ensures we only affect the state if the `uid` is the expected one on the store.
Fixes #1516
=> fix: uid check on upload/download state changes

src/components/settings/FileBrowserSettings.vue, src/components/widgets/filesystem/FileSystemBrowser.vue, src/locales/en.yaml, src/store/config/state.ts, src/store/config/types.ts
Adds a new setting that enables or disables drag & drop of files and folders in the File Browser.
Resolves #1521
=> feat: adds setting for files and folders drag & drop

src/components/widgets/filesystem/setupMonaco.ts
Adds support for regions in Klipper and Moonraker configuration files:
- `#region` will start a new region
- `#endregion` will close the last open region
Regions can contain other regions inside and the editor will collapse them correctly.
=> feat: adds config file #region folding support

src/components/widgets/toolhead/ToolheadPosition.vue
Only disable absolute position input controls when printer is in "printing" state (so we will keep then available if printer is "paused" or "busy")
Fixes #1531
=> fix: toolhead position controls enabled on pause

src/components/widgets/camera/CameraItem.vue, src/components/widgets/camera/services/DeviceCamera.vue, src/components/widgets/camera/services/IframeCamera.vue, src/components/widgets/camera/services/IpstreamCamera.vue, src/components/widgets/camera/services/MjpegstreamerAdaptiveCamera.vue, src/components/widgets/camera/services/MjpegstreamerCamera.vue, src/components/widgets/camera/services/WebrtcCamerastreamerCamera.vue, src/components/widgets/camera/services/WebrtcGo2RtcCamera.vue, src/locales/en.yaml, src/mixins/camera.ts
When Device camera is selected in Spoolman, we will now show a small menu where the camera name is to allow the user to change the device camera:
By default, we will select the "environment facing" camera (on the phone/tablet that will be the back camera if available, on a computer it will be whatever camera it can find)
The last camera selected will be stored in the browser local storage so that it gets picked up again next time - without affecting other browsers/devices.
Resolves #1541
=> feat: allow user selection of device camera

src/components/widgets/toolhead/ToolChangeCommands.vue
Attempt to group and wrap tool change commands so that it doesn't overflow and hide the buttons.
Fixes #1526
=> fix: group and wrap tool change commands

src/components/common/SystemLayout.vue, src/components/layout/AppNavDrawer.vue, src/components/ui/AppTextFieldWithCopy.vue, src/components/widgets/filesystem/FileSystemUploadDialog.vue, src/router/index.ts
Adds a new Adjust Dashboard Layout button to the navigation sidebar, only visible on desktop mode (will not show on mobile)
The button will also only show for the Home and the Diagnostics pages as these are the only 2 editable dashboards we currently have (I've also applied this change to the existing Adjust Dashboard Layout on the right sidebar)
Resolves #1545
=> feat: adds Adjust Dashboard Layout sidebar button

src/components/common/PeripheralsDialog.vue, src/store/server/mutations.ts
* The can interface sent to the backend should be "can0", "can1", not "0" or "1".
Signed-off-by: XiaoK <xiaok@zxkxz.cn>
=> fix: Moonraker canbus uuid parameter

src/components/widgets/thermals/TemperatureTargets.vue
Only shows context-menu on right-click of heater empty space (menu will NOT be shown on left-click)
Fixes #1557
=> fix(Heaters): no context menu on left click

src/components/ui/AppTextFieldWithCopy.vue, src/scss/misc.scss, src/util/clipboard-copy.ts
The existing clipboard copy method relies on having `navigator.clipboard` access, however this is only available on "secure" https context, and always `undefined` on "non-secure" http context.
The fix here is to use an old deprecated method that seems to still work in browsers and under "non-secure" http context.
Fix #1556
=> fix: clipboard copy on non-secure context

src/components/widgets/spoolman/SpoolSelectionDialog.vue
Change the call to `SAVE_VARIABLE` in Spoolman integration to ensure we only use lower-case variable names.
Fixes: #1562
=> fix: lower case variable name for SAVE_VARIABLE

src/components/common/KlippyStatusCard.vue, src/components/common/SystemControl.vue, src/components/layout/AppBar.vue, src/components/settings/GeneralSettings.vue, src/locales/en.yaml, src/mixins/state.ts, src/store/config/state.ts, src/store/config/types.ts
Adds a new optional "Printer Power Device" setting that allows selection of a Moonraker power device controller that should then control the printer power.
Resolves #1566
=> feat: control printer power via Moonraker

src/components/widgets/camera/services/MjpegstreamerAdaptiveCamera.vue
Fixes a regression introduced by https://github.com/fluidd-core/fluidd/commit/552a4f625a5dc2c48ca82d2a62b2e637249e6611 where MJPEG-adaptive camera sources can't detect QR codes
=> fix(spoolman): QR code detection with MJPEG-adaptive camera sources

src/plugins/filters.ts, src/store/printer/getters.ts
This bug was introduced with the changes on 897e163bb9b39b91cd927e90c63cf77de53b0dfd, as printer settings are all lowercase keys however this was not ensured at the time of refactor.
Fixed #1581
=> fix: printer settings must use lowercase key

src/components/widgets/camera/CameraItem.vue
The changes in c7204460c3185d4003f4da98b72dfd9d7d064b71 replaced all internal links with named navigation, however it seems I missed one.
This fixes the problem by using a `router-link` with named navigation.
Fixed #1585
=> fix(Camera): full-screen link

src/util/get-file-paths.ts
This was caused by changes on 5984451912301d23f63ed6567ddefe7955e8445d, the extension should now be prefixed with "." and that is missing from the parser - this PR fixes that.
Fix #1589
=> fix(FileSystem): extension parsing

src/components/widgets/system/SystemOverviewCard.vue, src/store/printer/state.ts, src/store/printer/types.ts
Another issue introduced by 785baa713c1ff4a3949f7e7a4b9a6e859516533f...
By allowing the `printer.ìnfo` property to start as `undefined`, the state object is not making this a reactive property... initializing the property as `null` fixes the problem.
Fixes #1592
=> fix: ensure Kalico is correctly detected

src/components/widgets/jobs/JobsCard.vue
Bug was introduced by refactor done in a3ef5a22a43dc0caf495f4b6440b490781787e2a, where the file browser `name` property value was fixed to "dashboard" when in fact it should be "jobs" when on the Jobs page.
Fixes #1594
=> fix(FileSystem): show default metadata columns

src/store/files/actions.ts
When a new file is created/uploaded, we check if the root is "gcodes" and if the file is one of the gcode file types, and if so, we ask for the file metadata from Moonraker.
The problem is that the filename on the response is a path, not just a filename, so it can includes a folder tree!
This fixes the issue by overwriting the filename to make sure it is just a file name.
Fixes #1599
=> fix(FileSystem): filename on metadata response

src/components/widgets/toolhead/ToolheadCard.vue, src/store/printer/types.ts
Adds basic support for the `smart_effector` and `probe_eddy_current`, so that the `PROBE_CALIBRATE` command is enabled.
Related to #1604
=> feat: adds basic support for smart_effector and probe_eddy_current

src/components/widgets/filesystem/FileSystem.vue, src/store/files/actions.ts, src/store/helpers.ts
For a long time now, we force the load of the metadata for the current printing file, and that works fine.
However, the way that the files store works, we store files and folders information on an object with root path as key - and loading the metadata for a file whose folder does not exist on the object would just discard said data!
To fix this, we will now ensure we load the full file parent directory (which will include the metadata for all files) instead of just the metadata for this specific file.
Fixes #1603 and #1606
=> fix: get directory for current printing file

src/components/widgets/camera/CameraItem.vue, src/components/widgets/camera/services/IpstreamCamera.vue, src/components/widgets/camera/services/MjpegstreamerAdaptiveCamera.vue, src/mixins/camera.ts
Ensures that frame event is always raised by handling it directly on the camera mixin (and allowing to override this on the implementations)
Fixes #1616
=> fix(Cameras): always emit frame event

src/store/files/getters.ts
The `filament_name` and `filament_type` metadata should now be converted to array from the string values we get from Moonraker; while we are doing this correctly for `files/getDirectory` and `history/getHistory`, it is missing on `files/getFile`.
Fixes #1622
=> fix(FileSystem): metadata types on getFile

src/components/ui/AppBtnToggle.vue
This bug was introduced with changes on 15f79fae0a8f2792d885e1caf0f0e817463972f7, where the new `AppBtnToggle` class was missing the required v-model declaration.
Fixes #1626
=> fix(AppBtnToggle): specify v-model property

src/store/printer/getters.ts
This issue was introduced with the changes on 897e163bb9b39b91cd927e90c63cf77de53b0dfd, settings keys are lowercase and this was missing here!
Fixes #1628
=> fix(Thermals): show extra sensor data

src/components/ui/AppDragIcon.vue, src/components/widgets/filesystem/FileSystem.vue, src/components/widgets/filesystem/FileSystemBrowser.vue, src/components/widgets/history/JobHistory.vue, src/components/widgets/job-queue/JobQueue.vue, src/components/widgets/job-queue/JobQueueBrowser.vue, src/components/widgets/job-queue/JobQueueCard.vue, src/components/widgets/spoolman/SpoolSelectionDialog.vue, src/locales/en.yaml, src/store/files/getters.ts, src/store/files/mutations.ts, src/store/files/state.ts, src/store/files/types.ts, src/store/helpers.ts, src/store/history/actions.ts, src/store/jobQueue/actions.ts, src/store/jobQueue/getters.ts, src/store/jobQueue/mutations.ts, src/store/jobQueue/state.ts, src/store/jobQueue/types.ts, src/views/Jobs.vue
Shows the job queue totals (filament length and weight, total estimated print time, and estimated finishing time) as a footer of the Job Queue card.
Part of the code changes on this PR is to allow partial file metadata load (thus marking the cache as `partial: true` to ensure that the file browser will force a directory refresh if needed) and so we now have the full metadata available on each queued job - which allows to show the thumbnail (implemented) and any other data column that we wish for (not done as of this PR)
Queued jobs that we can't find the file for will be shown in grey (just like the Job History when associated files are missing) and show the "missing file" icon.
When there are missing files, we show a warning label on the bottom with the count and disable drag & drop …
=> feat: show job queue totals

src/components/settings/FileEditorSettings.vue, src/components/widgets/filesystem/FileSystem.vue, src/locales/en.yaml, src/store/config/state.ts, src/store/config/types.ts, src/store/server/getters.ts
Allows configuring Klipper Save & Restart action:
- Firmware Restart (the default and current behavior, asks Moonraker to send `FIRMWARE_RESTART`)
- Host Restart (asks Moonraker to send `RESTART`)
- Service Restart (asks Moonraker to restart Klipper service - something I do manually when using Simulavr...)
Resolve #1646
=> feat: configurable Klipper Save & Restart action

src/components/settings/VersionSettings.vue, src/store/version/getters.ts
Since [this](https://github.com/Arksine/moonraker/commit/50e1f3c0c4da92ed90f1014861b042c5c50d3bf0), Moonraker now sends a "name" property as part of the "system" updates and that broke the way we check if OS updates are available or not.
Easy fix is to check the name!
Fixes #1652
=> fix: incorrect update status on system packages

src/components/ui/AppBtnToolheadMove.vue
This bug was introduced by the changes in ca087b7aff306cda71a076d1984014f76a58e85e, when the `v-on="$listeners"` directive was added, the `@click="$emit('click')"` should have been removed - which is exactly what this PR does!
Fixes #1663
=> fix: raise click event only once

src/components/widgets/filesystem/FileSystemBrowser.vue, src/components/widgets/filesystem/FileSystemToolbar.vue, src/components/widgets/history/JobHistory.vue, src/components/widgets/job-queue/JobQueueBrowser.vue, src/components/widgets/job-queue/JobQueueToolbar.vue, src/store/config/actions.ts, src/store/config/mutations.ts, src/store/config/state.ts, src/store/config/types.ts
We currently only allow configuring the thumbnail size for the Jobs, this change allow it to be configurable also on the Job History and Job Queue lists.
Related with #1667
=> feat: adjustable thumbnail size on Job Queue and History

src/components/widgets/job-queue/JobQueueBrowser.vue
If the printer is printing or paused, take the current printing job ETA as base to calculate the Job Queue ETA
Related with https://github.com/fluidd-core/fluidd/issues/1667
=> feat(JobQueue): use current print ETA in queue ETA

src/components/settings/VersionSettings.vue, src/store/version/getters.ts, src/store/version/types.ts
This adds basic support for the python packages updates in Moonraker Update Manager.
Resolves #1670
=> feat(Updates): adds python packages support

src/components/widgets/mmu/MmuEditTtgMapDialog.vue
The `AppFile.filename` attribute is related to the just the filename (no path) as returned by moonraker - this PR replaces it with the full path + filename to fix the issue.
Fixes #1675
=> fix: use path & filename in MmuEditTtgMapDialog

src/util/string-formatters.ts
As it currently stands, any negative value would be shown as the lowest possible unit - so 1000m is shown as 1km, but -1000m would be incorrectly shown as 1μm.
This fixes by using absolute ranges when formatting numbers.
Fixes #1686
=> fix: negative values formatting

src/components/widgets/filesystem/setupMonaco.features.ts, src/components/widgets/filesystem/setupMonaco.ts
This pull request enhances the Monaco editor integration for `klipper-config` files by adding improved symbol navigation and document structure awareness. The main changes introduce a document symbol provider to support outline and symbol navigation features, and ensure the necessary Monaco quick access functionality is included.
**Monaco Editor Feature Enhancements:**
* Added import for `standaloneGotoSymbolQuickAccess.js` to enable symbol navigation (e.g., "Go to Symbol") in the Monaco editor.
**klipper-config Language Support:**
* Registered a document symbol provider for `klipper-config` files, allowing the editor to display sections and properties in the outline view and support symbol navigation. This groups lines into sections (as namespaces) and properties (as child symbols), …
=> feat: adds config editor symbol support

src/components/settings/VersionSettings.vue, src/components/settings/VersionStatus.vue
Always show the update status info icon regardless of the error status
Fixes #1697
=> fix: always show update status indicator

src/components/common/ScrewsTiltAdjustDialog.vue, src/store/printer/getters.ts, src/store/printer/types.ts
Displays the relative Z position of each screw in the Screws Tilt Adjust dialog, making it easier to compare screw heights.
The relative Z is calculated based on the base screw's Z value and shown alongside the absolute Z in the UI.
Resolves #1703
=> feat: show relative Z in Screws Tilt Adjust dialog
