src/components/cards/FileSystemCard.vue
src/components/widgets/filesystem/FileSystemBrowser.vue
src/components/widgets/filesystem/FileSystemControls.vue

This is disabled for "upload & print" button.

feat: Allow multiple files upload from upload button.

---

src/plugins/filters.ts

44 cm was reported as 0.44mm, it's now reported as 440mm
Fixes #70

fix: Filament reporting under 1m

---

.github/workflows/multiarch_dockerhub.yml
docs/docker/Dockerfile
docs/docker/client.conf
docs/docker/common_vars.conf
docs/docker/upstreams.conf.template

- workflow untested (will fix as it runs...)
- add Dockerfile for deployment in nginx-alpine container
- build for x64, ARM32v7, ARM64
- use multistage build for small image size (13mb)
- configure gzip & jpegstreamer proxy
- allow passing jpegstreamer ip & port through env variables
You'll need to provide dockerhub user & password/token through github secrets for the workflow

add Dockerfile & Github workflow

---

.github/workflows/build.yml
src/plugins/filters.ts
tests/unit/example.spec.ts
tests/unit/filters.spec.ts

chore: Unit tests - WIP

---

src/components/cards/settings/TemperaturePresetSettingsCard.vue
src/components/widgets/TemperatureTargetsWidget.vue
src/store/config/getters.ts
src/store/config/mutations.ts
src/store/config/types.ts

Sort Temperature presets in UI Settings and Dashboard Thermals Widget
Signed-off-by: Joel Nimety <jnimety@gmail.com>

feat: sort TemperaturePresets

---

src/locales/ru.yaml
src/store/config/index.ts

I have made the translation into russian

Russian language added

---

src/locales/de.yaml
src/store/config/index.ts

I have made the translation into german once

german language added

---

src/locales/pt.yaml
src/store/config/index.ts

Upload pt.yaml

---

src/locales/ko.yaml
src/store/config/index.ts

Thanks to `Ewan_Shin V2.841` from the Voron Discord for the trans.

feature(korean): Added Korean language

---

src/locales/ko.yaml

Thanks to Ewan_Shin V2.841 on the Voron Discord.

chore: Added "Enable notifications" for korean

---

src/locales/de.yaml

feat: Missing translations in German
Added missing translations
Signed-off-by: Mario Perini <info@marioperini.ch>

added missing translations (de)

---

src/locales/es.yaml
src/store/config/index.ts

Based on #229, added missing keys

feature(es): Added Spanish

---

src/components/common/SystemControl.vue
src/components/settings/VersionSettings.vue
src/components/widgets/console/ConsoleCommand.vue
src/components/widgets/thermals/TemperatureCard.vue
src/components/widgets/thermals/TemperaturePresetsMenu.vue
src/locales/en.yaml
src/locales/fr.yaml

chore: Added missing keys

---

src/locales/pt.yaml

Update some translations for Portuguese

Portuguese translation

---

src/locales/ko.yaml

I found some keys are shown as it is in Korean localization. I copied keys from latest English locale and did simple diff to find missing keys and add few more translation rather than using English.

Update Korean localization for missing keys.

---

src/locales/it.yaml

also adds better formatting to the .yaml document
Signed-off-by: Stefano Serioli <stefano.serioli@outlook.it>

feat(i18n-IT): add missing keys to IT translation

---

src/locales/nl.yaml

Signed-off-by: Leandro Marceddu <leandromarceddu@gmail.com>

Updated NL translations

---

src/components/widgets/retract/Retract.vue
src/components/widgets/retract/RetractCard.vue
src/globals.ts
src/locales/en.yaml
src/store/layout/index.ts
src/store/printer/index.ts
src/views/Dashboard.vue

My JS code may look ugly because I never worked with him before.
This PR can be reviewed only as an idea, but if anyone can advise me on how to improve code I'll do my best.

Add Firmware Retraction card.

---

src/locales/uk.yaml
src/store/config/index.ts

Added missing Ukrainian translation. It is Finished.

Added Ukrainian translation

---

src/locales/it.yaml

Signed-off-by: Stefano Serioli <stefano.serioli@outlook.com>

feat(i18n-IT): update Italian translations

---

src/locales/ko.yaml

some string need to translate more

Update ko.yaml and added missing strings

---

src/locales/ar.yaml
src/store/config/index.ts

Add Arabic Language Support

---

src/locales/fr.yaml

Adds missing translations in french.

l10n: update french translations

---

src/locales/es.yaml

feat: Updated Spanish translation.
A lot of the translations where either missing, completely wrong, had typos or were weirdly worded. I've done my best to try to maintain a consistent style, but context was hard to deduce in some of the strings so there will probably be some less than ideal translations.
Signed-off-by: Zhant <zhantyzgz@gmail.com>

Updated Spanish translation

---

docs/installation/fluiddpi.md

Fixed URL in step 5

---

src/locales/cn.yaml

中文翻译补全和优化，由 sjqlwy 和 Creeper_MZ 协作完成。
Update Simplified Chinese translation, collaborated by sjqlwy & Creeper_MZ

Update Simplified Chinese translation

---

src/locales/es.yaml

Fix: Spanish translate file

---

src/store/printer/getters.ts

Follow up on #379 that introduced an unused variable build warning.

Fix build warnings

---

src/components/widgets/toolhead/ToolheadMoves.vue
src/mixins/toolhead.ts
src/store/printer/getters.ts

Give the possibility to move an axis if the others are not homed.
like that:
instead of that:
Signed-off by Biorn : biorn@me.com

Feat: make each axis controllable after homing

---

src/components/settings/macros/MacroSettingsDialog.vue
src/components/widgets/macros/Macros.vue
src/locales/en.yaml
src/store/macros/getters.ts
src/store/macros/types.ts

Signed-off-by: biorn biorn@me.com

Feat: alias for macro

---

src/components/settings/GeneralSettings.vue
src/locales/en.yaml
src/store/config/index.ts

signed-off-by: biorn1950 <biorn@me.com>

Fix: typo Date Time Format

---

src/components/widgets/toolhead/ToolheadPosition.vue

Relative to: https://github.com/fluidd-core/fluidd/issues/467 and https://github.com/fluidd-core/fluidd/issues/427
Signed_off_by: Biorn1950 <biorn@me.com>

Fix: Z move speed issue

---

src/components/widgets/retract/Retract.vue

- if value < 0.25 was rounding to 0 the max value.
( fix #366)
Signed-off-by: Biorn <biorn@me.com>

 Fix: firmware retractation length stuck at 0

---

src/components/widgets/toolhead/ToolheadPosition.vue

Signed-of-by: Biorn <biorn@me.com>

feat: disable position field if not homed

---

package-lock.json
package.json
src/components/settings/auth/ApiKeyDialog.vue
src/components/ui/AppQrCode.vue

Fixes #411 
Adds new dependency to [qrcode.vue](https://www.npmjs.com/package/qrcode.vue)

feat: show qr-code with api key

---

src/components/widgets/camera/CameraItem.vue
src/globals.ts

Signed-off-by: Matthew Lloyd <github@matthewlloyd.net>

feat: Add full-screen button to camera view

---

src/components/widgets/macros/Macros.vue

Fix #545
Signed-of-by: Biorn1950 <biorn@me.com>

Fix: Alias for uncategorized macro

---

src/components/widgets/toolhead/ZHeightAdjust.vue

Changing the condition of the probe check.
fix #546
Signed-of-by: Biorn1950 <biorn@me.com>

fix: z-offset apply

---

src/components/settings/macros/MacroCategories.vue
src/locales/en.yaml
src/views/Configure.vue

Follow up on https://github.com/fluidd-core/fluidd/pull/556#issuecomment-1057625134

feat: adds some missing i18n keys

---

src/plugins/colorSet.ts
src/plugins/filters.ts

Some minor improvements on the TypeScript typings.
On a side note, I do wish we could do more/better, but unfortunately, we are limited by the horrible TypeScript support in Vue 2...

fix: typescript typings

---

src/locales/de.yaml

Adds all missing translations for current features (except for `app.console.placeholder.scroll`, which doesn't seem to be used anymore).  Fixes and improves some other translations (see linked issue) (some changes only for layout fixes).
Closes #561

chore(i18n): improve, fix and finish german translations

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

chore: updates GitHub issue templates

---

src/components/widgets/status/StatusTab.vue

fix: individual object layer count

---

src/locales/hu.yaml

Hello!
I don't know who started updating the Hungarian language, but I now dared to take over the correction and updating of the translation.
In my experience, there were many gaps and several incorrect translations in the file.
- I corrected incorrect translations. (However, there may still be errors.)
- I have included translations of the newly added new options.
- I have translated the old and new error messages that appear.
- The translation is currently 100% ready.
Signed-off-by: AntoszHUN <zsikaiantal@gmail.com>

Update Hungarian language

---

src/locales/de.yaml
src/locales/en.yaml

Required for https://github.com/fluidd-core/fluidd/commit/1d587699394d1b37e90cf3317409ab375a440eda

fix(i18n): add missing 'cancelled' translation

---

src/components/widgets/thermals/TemperatureTargets.vue

As requested in https://github.com/fluidd-core/fluidd/pull/496#issuecomment-1066193995
Also fixes an oversight where `temperature_fan`s were missing the ROC column, IMO not worthy of its own PR

feat(thermals): display rate of change for all temperature sensors

---

src/init.ts

fix: auto-determination of base printer

---

src/store/config/index.ts

fix(i18n-PT): use localized label

---

src/locales/ja.yaml
src/store/config/index.ts

Add new Japanese translation.
Signed-off-by: Suisyan <99475190+Suisyan@users.noreply.github.com>

feat(i18n-JA): adds Japanese language

---

src/components/settings/ToolheadSettings.vue
src/components/widgets/toolhead/ToolheadMoves.vue
src/locales/de.yaml
src/locales/en.yaml
src/store/config/index.ts
src/store/config/mutations.ts
src/store/config/types.ts

feat: adjustable toolhead move distances

---

src/components/widgets/thermals/TemperatureTargets.vue
src/locales/en.yaml
src/store/printer/getters.ts
src/store/printer/types.ts

Here's how it is currently showing the humidity output from a BME280 connected to a Pi Zero 2W running as MCU:
Fixes #335, fixes #397, fixes #434

feat: show pressure and humidity from sensors

---

src/components/settings/FileEditorSettings.vue

feat: add Reset button to File Editor settings

---

src/components/settings/ToolheadSettings.vue

fix: improves ToolheadSettings rules and validation

---

src/plugins/vuetify.ts
vue.config.js

Follows [these instructions](https://vuetifyjs.com/en/features/treeshaking/#importing-from-lib) to ensure we only bundle what we use!
[Before](https://github.com/fluidd-core/fluidd/runs/5612223044?check_suite_focus=true#step:7:12):
[After](https://github.com/fluidd-core/fluidd/runs/5612897507?check_suite_focus=true#step:7:12):

chore: vuetify tree-shaking

---

src/components/layout/AppNavDrawer.vue
src/components/widgets/console/ConsoleCard.vue
src/router/index.ts
src/views/Console.vue

feat: add full-screen console view

---

src/components/widgets/jobs/JobsCard.vue

For consistency with the console card:
Signed-off-by: Matthew Lloyd <github@matthewlloyd.net>

feat: add full-screen button to the Jobs card

---

src/components/widgets/filesystem/FileSystemContextMenu.vue

fix: typescript type narrowing

---

src/components/widgets/gcode-preview/GcodePreviewCard.vue
src/locales/ar.yaml
src/locales/cz.yaml
src/locales/de.yaml
src/locales/en.yaml
src/locales/es.yaml
src/locales/hu.yaml
src/locales/it.yaml
src/locales/ja.yaml
src/locales/ko.yaml
src/locales/ru.yaml
src/store/layout/index.ts

feat: graduates g-code previewer to non-beta

---

src/components/layout/AppNotificationMenu.vue
src/components/widgets/camera/CameraItem.vue
src/components/widgets/filesystem/FileEditorTextOnly.vue
src/components/widgets/status/ReprintTab.vue
src/scss/file-system.scss

Closes #673 
---
Screenshots of the new styling (light and dark theme):
---
---
---

fix(style): light theme fixes/improvements

---

src/store/history/actions.ts

fix: job card history metadata race condition

---

src/components/widgets/console/ConsoleCard.vue
src/store/console/actions.ts
src/store/console/getters.ts
src/store/console/index.ts
src/store/console/mutations.ts
src/store/console/types.ts

feat: clear console

---

src/components/widgets/gcode-preview/GcodePreviewControls.vue

fix: clear "follow progress" if not correct file printing

---

src/components/settings/timelapse/subsettings/CustomParkPositionSettings.vue

As reported by `yasas.alwis#1667` on Discord

fix: timelapse custom park position

---

src/components/widgets/thermals/TemperatureCard.vue
src/components/widgets/thermals/TemperatureTargets.vue
src/locales/de.yaml
src/locales/en.yaml
src/store/config/index.ts
src/store/config/types.ts

feat: add toggles for relative humidity / barometric pressure

---

src/components/widgets/filesystem/setupMonaco.ts

Improves editor code folding, by splitting the code into section blocks folding, and comment blocks folding.
Includes both `;` and `#` as comment prefixes.
Fixes #691

fix: code editor folding

---

src/locales/zh-HK.yaml
src/store/config/index.ts

I updated the Traditional Chineselanguage pack.
I updated everything.
I checked for translation errors.
Thanks!
Signed-off-by: jxky2004@gmail.com

Update Traditional Chinese language pack.

---

src/locales/de.yaml
src/locales/en.yaml

Syncs German translations to new English keys; removes a stale key from the English translations

feat(i18n-DE): update German translations

---

src/globals.ts

This pull request is to extend config file mapping and include affected services of our project, the telegram bot.
Signed-off-by: Nick Lefskiy [n.lefskiy@yandex.ru](mailto:n.lefskiy@yandex.ru)

feat: moonraker-telegram-bot config and service mapping

---

src/components/layout/AppBar.vue
src/components/settings/GeneralSettings.vue
src/locales/en.yaml
src/store/config/index.ts
src/store/config/types.ts

feat: Save Config And Restart button visibility toggle

---

src/components/widgets/toolhead/ZHeightAdjust.vue

Refactors ZHeightAdjust.vue to clear typing warnings.

chore: code refactor & cleanup

---

package-lock.json
package.json

Fixes regression of #615 caused by 3e08de78

chore: update vue-echarts

---

src/api/httpClient.ts
src/api/socketActions.ts
src/components/widgets/gcode-preview/GcodePreviewCard.vue
src/components/widgets/system/SystemLoadChart.vue
src/init.ts
src/mixins/files.ts
src/plugins/i18n.ts
src/plugins/socketClient.ts
src/router/index.ts
src/store/auth/actions.ts
src/store/auth/helpers.ts
src/store/chart_helpers.ts
src/store/charts/actions.ts
src/store/charts/getters.ts
src/store/console/getters.ts
src/store/files/actions.ts
src/store/files/getters.ts
src/store/helpers.ts
src/store/index.ts
src/store/macros/getters.ts
src/store/mesh/getters.ts
src/store/notifications/types.ts
src/store/printer/actions.ts
src/store/printer/getters.ts
src/store/types.ts
src/store/version/getters.ts

I've notice `RootState` was missing quite a few properties from it (new modules added to store that were not mentioned on it), so I added those and remove the optional notation (`?`) as these are always defined by the module (as long as the module is added, the properties have values!).

chore: improve RootState typings

---

src/components/widgets/bedmesh/BedMeshCard.vue
src/store/layout/index.ts
src/views/Dashboard.vue
src/views/Tune.vue

feat: allow showing Bed Mesh on Dashboard

---

src/locales/de.yaml

feat(i18n-DE): update German translation

---

src/components/widgets/filesystem/FileSystem.vue
src/components/widgets/filesystem/FileSystemBrowser.vue
src/components/widgets/filesystem/FileSystemFilterMenu.vue
src/components/widgets/filesystem/FileSystemToolbar.vue
src/locales/en.yaml
src/store/config/index.ts
src/store/config/types.ts
src/store/files/getters.ts
src/store/files/types.ts
src/views/Configure.vue

Closes: #768 
Demo:
https://user-images.githubusercontent.com/44060099/182890156-92f1d41c-367d-445c-86c9-3104bb0d70c5.mov

feat(ui): Hide files in /config

---

src/api/socketActions.ts
src/components/settings/VersionSettings.vue
src/locales/de.yaml
src/locales/en.yaml
src/store/version/actions.ts

feat(ui): update all feature

---

src/scss/misc.scss
src/views/Dashboard.vue

Changes based on [this work](https://github.com/fluidd-core/fluidd/commit/8a152ef907c20f54f4bc17304d5d16b44ccf7c7d) from @matmen, all I did was move the constraint directly to the Dashboard.vue file only
Fixes #762

fix: dashboard constrained width

---

src/components/widgets/filesystem/FileEditor.vue
vue.config.js

feat: enable context menu in monaco editor

---

src/locales/hu.yaml

I updated the Hungarian language package.
- The Hungarian subtitles have been updated.
- I also made translation mistakes.
- I also translated the texts that were included earlier.
- I also translated the text that was added in the past few days.
As soon as the package is merged, I will correct the newly added words. It may be longer than English or Chinese. Therefore, it may cause errors.
Signed-off-by: AntoszHUN <zsikaiantal@gmail.com>

feat(i18n-HU): update Hungarian language files

---

src/locales/es.yaml

Hello, I've updated some translations. One thing to be aware is that BabelEdit quoted some strings.
Thanks!
Signed-off-by: Luis Diaz <Luis.Diaz@lucrecio.cloud>

partial ES translation updates

---

src/locales/de.yaml
src/locales/en.yaml
src/store/charts/mutations.ts

Marks the feature as beta and fixes two small mistakes

chore: Diagnostics panel tweaks

---

src/components/ui/AppSlider.vue

do not escape label for app-slider

---

src/components/ui/AppBtnCollapseGroup.vue
src/components/widgets/filesystem/FileSystemBrowser.vue
src/components/widgets/filesystem/FileSystemToolbar.vue
src/globals.ts
src/locales/en.yaml
src/store/config/index.ts
src/store/config/types.ts

feat: adjustable thumbnail size

---

src/locales/hu.yaml

I have updated the newly added function.
- Hungarian translation of the newly added function.
- New function: Change thumbnail size.
Signed-off-by: AntoszHUN <zsikaiantal@gmail.com>

feat(i18n-HU): Update Hungarian Language

---

src/components/widgets/camera/CameraItem.vue

fix: destroy mjpg camera stream properly

---

src/components/widgets/gcode-preview/GcodePreviewCard.vue

fix: only auto-load gcode preview on ongoing print

---

src/api/socketActions.ts
src/components/widgets/endstops/EndStopsCard.vue
src/globals.ts
src/store/printer/getters.ts
src/store/printer/types.ts

feat: Adds any existing Probe to Endstops card

---

src/components/widgets/exclude-objects/ExcludeObjects.vue

fix: Exclude Object not reacting to mobile inputs

---

src/mixins/files.ts

Following up on the work from @matmen, I found that we can do a small optimization so that we only request one-shot tokens when required instead of doing it all the time as we do right now!

chore: only request oneshot token when required

---

src/components/common/ManualProbeDialog.vue

fix: sort the manual probe offsets descending

---

src/store/config/getters.ts

feat: sort instance list alphabetically

---

src/locales/ru.yaml

Updating russian translation.
Signed-off-by: V.Zemlyakov zemlyakov@bmstu.ru

feat(i18n-RU): Update Russian translations

---

src/components/ui/AppMacroBtn.vue

tested locally. works as expected

feat: send on enter

---

vite.config.ts

fix: add moonraker routes to workbox.navigateFallbackDenylist

---

src/store/printer/getters.ts

fix: check type when filtering prefixed sensors

---

src/App.vue
src/api/httpClientActions.ts
src/components/widgets/filesystem/FileSystem.vue
src/components/widgets/timelapse/TimelapseStatusCard.vue
src/mixins/files.ts

fix: encode all request paths

---

src/locales/zh-CN.yaml
src/locales/zh-HK.yaml

updates Chinese translations
Signed-off-by: Ercsion <bhs5612@gmail.com>

feat(i18n-zh): updates Chinese translations

---

src/locales/uk.yaml

feat: Fixed some typos and added missing translations.
Signed-off-by: Entraft pasinc23@gmail.com

feat(i18n-UK): update Ukrainian translations

---

src/components/layout/AppUserMenu.vue
src/components/ui/AppColumnPicker.vue
src/components/widgets/camera/CameraMenu.vue
src/components/widgets/console/ConsoleCard.vue
src/components/widgets/filesystem/FileSystemContextMenu.vue
src/components/widgets/filesystem/FileSystemFilterMenu.vue
src/components/widgets/filesystem/FileSystemMenu.vue
src/components/widgets/job-queue/JobQueueContextMenu.vue
src/components/widgets/status/PauseResumeBtn.vue
src/components/widgets/thermals/TemperatureCard.vue
src/components/widgets/thermals/TemperaturePresetsMenu.vue

(no change)
(no change)
(obsolete)
(no change)
Fixes #912

style: consolidate menu styling

---

src/locales/zh-HK.yaml

I updated the Traditional Chineselanguage pack.
I updated everything.
I checked for translation errors.
Thanks!
Signed-off-by: jxky2004@gmail.com

feat(i18n-zh-HK): update Traditional Chinese translations

---

src/components/widgets/toolhead/ToolheadCard.vue

If there is an `UNLOAD_FILAMENT` macro, that will be shown in the Tools menu; if not, if there is an `M702` macro, that will be shown in the Tools menu (as "M702 (Unload filament)")
Similarly, if there is a `LOAD_FILAMENT` macro, that will be shown in the Tools menu; if not, if there is an `M701` macro, that will be shown in the Tools menu (as "M701 (Load filament)")
(Priority will always be given to `UNLOAD_FILAMENT` and `LOAD_FILAMENT` macros)

feat: adds load/unload filament support

---

src/components/widgets/filesystem/FileSystem.vue
src/locales/en.yaml

We already allowed to filter hidden files, this now adds folders to the filter!
Fixes #1082

feat: filter hidden folders as well as files

---

components.d.ts
src/components/ui/AppColumnPicker.vue
src/components/ui/AppThumbnailSize.vue
src/components/widgets/filesystem/FileSystemToolbar.vue
src/globals.ts
src/locales/en.yaml
src/store/files/getters.ts

fix: adds missing File Browser button tooltips

---

src/components/widgets/filesystem/FileSystem.vue
src/locales/ar.yaml
src/locales/cs.yaml
src/locales/de.yaml
src/locales/en.yaml
src/locales/es.yaml
src/locales/fr.yaml
src/locales/hu.yaml
src/locales/it.yaml
src/locales/ja.yaml
src/locales/ko.yaml
src/locales/nl.yaml
src/locales/pt.yaml
src/locales/sl.yaml
src/locales/uk.yaml
src/locales/zh-CN.yaml
src/locales/zh-HK.yaml

Improves "delete item/items" confirmation message
Fixes #1080

i18n: improves delete confirmation message

---

src/locales/ja.yaml

Japanese language update.
Signed-off-by: Suisyan 99475190+Suisyan@users.noreply.github.com

feat(i18n-JA): update Japanese language

---

src/components/settings/cameras/CameraConfigDialog.vue
src/components/widgets/camera/CameraItem.vue
src/locales/en.yaml
src/store/cameras/types.ts

Adds WebRTC camera streaming support, specific for Crowsnest `camera-streamer`.
https://crowsnest.mainsail.xyz/configuration/cam-section

feat: adds WebRTC (camera-streamer) support

---

src/globals.ts
src/locales/pl.yaml

feat(i18n-PL): adds Polish translations

---

src/locales/pl.yaml

Signed-off-by: Daviteusz <daviteusz0@gmail.com>

feat(i18n-PL): update Polish translations

---

src/globals.ts
src/locales/af.yaml

feat: Afrikaans translation added
New Afrikaans Locale file added.
Signed-off-by: Males <males.tomlinson@gmail.com>

feat(i18n-AF): New Afrikaans locale added

---

src/components/widgets/thermals/TemperatureTargets.vue

We currently use the last (most recent) thermal history item and the 5th oldest from that and calculate the thermal change.
This was working fine as up until now the thermal history was always a valid number, however the TMC2240 can report `null`.
As such this PR changes the behavior to the following:
- Take the last (most recent) 5 thermal history items
- From right to left, take items until we find a `null`
- Calculate thermal change resulting from the change of the first (oldest) and the last (newest) thermal history items
Fixes #1138

fix: ignore null on thermal change calculation

---

src/plugins/colorSet.ts

Adds a few more colors for sensors in the temperature chart.
Fixes #1165

fix: adds more chart colors for sensors

---

docs/configuration/obico_for_remote_access.md

We have added a lot of stuff since the last update, including the full remote access to fluidd page.

 docs(obico): remote access page refresh #1176 

---

package-lock.json
package.json
src/api/httpClientActions.ts
src/components/common/AddInstanceDialog.vue
src/components/widgets/filesystem/FileSystem.vue
src/components/widgets/filesystem/FileSystemDownloadDialog.vue
src/components/widgets/filesystem/FileSystemUploadDialog.vue
src/mixins/files.ts
src/plugins/filters.ts
src/plugins/httpClient.ts
src/store/files/actions.ts
src/store/files/mutations.ts
src/store/files/state.ts
src/store/files/types.ts
tests/unit/setup.ts

Updated the axios dependency to the latest 1.x that is now stable enough for usage and introduces some nice new features!

chore: updates to the latest axios dependency

---

src/components/widgets/filesystem/FileSystem.vue
src/components/widgets/filesystem/FileSystemBrowser.vue
src/components/widgets/filesystem/FileSystemContextMenu.vue
src/components/widgets/history/JobHistory.vue
src/components/widgets/status/ReprintTab.vue
src/components/widgets/status/StatusTab.vue
src/mixins/files.ts
src/store/files/getters.ts
src/store/files/types.metadata.ts
src/store/files/types.ts

Refactors the file thumbnails code, including adding the capability to click on the currently printing file thumbnail in the Print Status card.
Resolves #1198

refactor: thumbnails code and typings

---

index.html
public/config.json
server/config.json
src/components/ui/AppIcon.vue
src/init.ts
src/store/config/getters.ts
src/store/config/state.ts

This will allow Fluidd to be build with the `--base` parameter.
The service worker will still NOT work as the default config expects "/" as base path.
Partial fix for #1206

fix: adds support for public base path

---

src/components/settings/VersionSettings.vue

Presents any warning or anomaly detected by Moonraker's Update Manager component.

feat: adds Update Manager warnings and anomalies support

---

.github/FUNDING.yml

chore: add funding link to org

---

src/components/widgets/filesystem/FileSystem.vue
src/components/widgets/filesystem/FileSystemFilterMenu.vue
src/locales/en.yaml
src/store/files/getters.ts
src/store/files/types.ts

fixes #1277
- add filter for moonraker backup files.

feat: add feature to filter moonraker backup files

---

src/store/printer/state.ts
src/views/Dashboard.vue

fix: makes print cooling fan optional

---

src/components/settings/ToolheadSettings.vue
src/components/widgets/toolhead/ToolheadControlCross.vue

fix: reset default move distance when availables change

---

src/components/settings/GeneralSettings.vue
src/plugins/filters.ts

fix: default to user language as Intl format

---

src/components/widgets/filesystem/FileSystemFilterMenu.vue

fix: file browser filters list

---

src/components/widgets/spoolman/SpoolSelectionDialog.vue
src/store/config/state.ts
src/store/config/types.ts

feat(spoolman): remember spool selection dialog sort key/order

---

src/components/widgets/filesystem/FileSystem.vue
src/components/widgets/filesystem/FileSystemToolbar.vue

fix: correctly show the active root

---

docs/features/thumbnails.md

Signed-off-by: Thijs Triemstra <info@collab.nl>

docs(thumbnails): prusa slicer syntax update

---

docs/configuration/octoeverywhere_free_remote_access.md

This PR updates the OctoEverywhere page with some features that have been added to the project!
signed-off-by: Quinn Damerell quinnd@outlook.com

docs(octoeverywhere): updating the docs with new project updates

---

src/components/widgets/thermals/TemperatureTargets.vue

fix(thermals): size columns dynamically, disallow line breaks

---

src/components/widgets/outputs/OutputPin.vue

Present the OutputPin value rounded to 2 decimals.
Related with #1343

fix: round OutputPin value

---

src/components/settings/GeneralSettings.vue
src/locales/en.yaml
src/store/config/state.ts
src/store/config/types.ts
src/store/printer/getters.ts

added options on general setting with file or slicer for finish time and progress 
close #1373 
file:
slicer:

feat: add finish time selection from slicer or file

---

src/components/settings/VersionSettings.vue

fix: disable Check Updates button if printer printing

---

src/components/widgets/spoolman/SpoolSelectionDialog.vue

Fixes https://github.com/fluidd-core/fluidd/issues/1384

fix(spoolman): missing filament material in selection dialog

---

src/components/widgets/runout-sensors/RunoutSensorsCard.vue
src/store/layout/state.ts
src/views/Dashboard.vue
src/views/Tune.vue

feat: allow showing Runout Sensors on Dashboard

---

src/globals.ts
src/locales/tr.yaml

Adds Turkish translations as provided by @fatih5228
Resolves #1392

feat(i18n-TR): Updates Turkish translations

---

src/store/printer/getters.ts

fix: progress not shown a number

---

src/components/widgets/filesystem/FileSystem.vue
src/components/widgets/filesystem/FileSystemBrowser.vue
src/components/widgets/history/JobHistoryItemStatus.vue
src/store/config/state.ts
src/store/files/types.metadata.ts
src/store/files/types.ts

Adds a "Status" column to the Jobs File Browser list
Resolves #1508

feat: adds status column to job files list

---

src/components/widgets/gcode-preview/GcodePreview.vue
src/components/widgets/gcode-preview/GcodePreviewButton.vue
src/components/widgets/gcode-preview/GcodePreviewCard.vue
src/store/config/state.ts
src/store/config/types.ts
src/store/gcodePreview/actions.ts
src/store/gcodePreview/getters.ts
src/store/gcodePreview/mutations.ts
src/store/gcodePreview/state.ts
src/store/gcodePreview/types.ts

Saves and restores all Gcode Previewer options
Resolves #1441

feat(GcodePreview): save & restore viewer state

---

src/components/widgets/history/JobHistory.vue
src/components/widgets/stats/PrinterStatsCard.vue
src/components/widgets/system/DiskUsageCard.vue

Corrects the model binding for the Job History search functionality.
Fixes #1532

fix: Job History search

---

src/globals.ts

Adds [Kalico](https://kalico.gg/) config support.

feat: adds Kalico config support

---

src/components/widgets/thermals/HeaterContextMenu.vue
src/components/widgets/thermals/HeaterMpcCalibrateDialog.vue
src/components/widgets/thermals/TemperatureTargets.vue
src/locales/en.yaml
src/store/printer/getters.ts

Adds Kalico's `MCP_CALIBRATE` support.
Resolves #1555

feat(Heaters): adds MPC_CALIBRATE support

---

src/api/socketActions.ts
src/components/widgets/spoolman/SpoolmanCard.vue
src/store/spoolman/actions.ts
src/store/spoolman/mutations.ts
src/store/spoolman/state.ts
src/store/spoolman/types.ts

Retrieves the currency from Spoolman settings and uses that to show the price of the filament.
Resolves #1583

feat(Spoolman): show currency for price field

---

src/components/ui/AppDraggable.vue
src/components/widgets/console/Console.vue
src/components/widgets/console/ConsoleCommand.vue
src/components/widgets/filesystem/FileSystem.vue
src/components/widgets/gcode-preview/GcodePreview.vue
src/components/widgets/job-queue/JobQueue.vue
src/components/widgets/job-queue/JobQueueBrowser.vue
src/components/widgets/job-queue/JobQueueCard.vue
src/components/widgets/jobs/JobsCard.vue
src/components/widgets/timelapse/TimelapseSettingsCard.vue
src/components/widgets/timelapse/TimelapseStatusCard.vue
src/views/Configure.vue
src/views/Dashboard.vue
src/views/Diagnostics.vue
src/views/History.vue
src/views/Jobs.vue
src/views/System.vue
src/views/Timelapse.vue
src/views/Tune.vue

Made the content in pages Configuration, Jobs, Console and Timelapse use the full vertical available space.
Also, I hate layout work...
Resolves #1571

style: layout changes to allow full height

---

src/components/widgets/gcode-preview/GcodePreviewCard.vue

fix(GcodePreview): auto-loading condition

---

src/components/settings/GeneralSettings.vue
src/components/settings/SpoolmanSettings.vue
src/components/widgets/spoolman/QRReader.vue
src/components/widgets/spoolman/SpoolSelectionDialog.vue
src/components/widgets/spoolman/SpoolmanCard.vue
src/components/widgets/toolhead/ToolChangeCommands.vue
src/locales/en.yaml
src/plugins/filters.ts
src/plugins/i18n.ts
src/store/spoolman/actions.ts
src/store/spoolman/getters.ts
src/store/spoolman/mutations.ts
src/store/spoolman/state.ts
src/store/spoolman/types.ts
src/util/__tests__/date-time-formatters.spec.ts
src/util/date-time-formatters.ts
src/util/string-formatters.ts

feat(Spoolman): adds new metadata

---

src/components/widgets/stats/PrinterStatsCard.vue
src/components/widgets/thermals/TemperatureTargets.vue
src/locales/en.yaml
src/store/config/state.ts
src/store/config/types.ts
src/util/date-time-formatters.ts
src/util/string-formatters.ts

feat: optional history totals in days and kilometers

---

components.d.ts
src/components/layout/AppObservedColumn.vue
src/components/ui/AppBtnCollapseGroup.vue
src/components/widgets/gcode-preview/GcodePreviewCard.vue
src/components/widgets/history/PrintHistoryCard.vue
src/components/widgets/job-queue/JobQueueCard.vue
src/components/widgets/stats/PrinterStatsCard.vue
src/components/widgets/thermals/TemperatureCard.vue
src/components/widgets/thermals/ThermalChart.vue
src/components/widgets/toolhead/ToolheadCard.vue
src/views/Dashboard.vue

Allows dynamically adapting Dashboard cards to their available width.
Resolves #1437

feat: check cards for narrow width

---

src/components/widgets/spoolman/SpoolmanCard.vue
src/store/spoolman/getters.ts
src/store/spoolman/types.ts

feat(Spoolman): spool progress indicator in card

---

docs/development/index.md

docs: fix typo

---

src/components/widgets/camera/services/WebrtcCamerastreamerCamera.vue

Follow up on https://github.com/ayufan/camera-streamer/issues/55#issuecomment-3035240444

feat(WebrtcCamerastreamer): adds ping/pong support
